name = "Matroid"
keywords = ["math"]
defaultTargets = ["Matroid"]
enableArtifactCache = true

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
pp.proofs.withType = false
linter.docPrime = false
linter.style.longLine = true
linter.unusedSimpArgs = true
# Transition aid while migrating to the module system (private decls used from public sections)
backward.privateInPublic = true

[[require]]
name = "loogle"
git = "https://github.com/nomeata/loogle"
rev = "master"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "Matroid"
