module

public import Matroid.Graph.Degree.Max
public import Matroid.Graph.Minor.Defs
public import Matroid.Graph.Planarity.Realization.Iso
public import Matroid.Graph.Planarity.Realization.Subgraph
public import Matroid.Graph.TopologicalMinor
public import Mathlib.Analysis.Convex.PathConnected
public import Mathlib.LinearAlgebra.LinearIndependent.Basic

@[expose] public section

/-!
# Drawings of graphs

This file defines drawings as continuous injections from the weak realization of a graph and
provides their basic constructions and transport lemmas.

## Main definitions

- `Graph.Drawing`: a continuous injection from the weak realization of a graph.
- `Graph.IsDrawable`: existence of a drawing in a specified topological space.
- `Graph.Planar`: existence of a drawing in the Euclidean plane.
- `Graph.Drawing.Face`: a connected component of the complement of a drawing.
- `Graph.Drawing.IsFacialSubgraph`: a subgraph whose drawing is the frontier of a face.

## Main statements

- `Graph.Drawing.ofVertexAndEdgePaths`: construct a drawing from pairwise internally disjoint edge
  paths.
- `Graph.Drawing.restrict`: restrict a drawing to a subgraph.
- `Graph.Drawing.ofIso`: transport a drawing along a graph isomorphism.

The drawing structure contains only continuity and injectivity. Finiteness and geometric
properties are supplied by the lemmas that use a drawing. `Planar` specializes `IsDrawable` to
`EuclideanSpace ℝ (Fin 2)`; plane-topology files use the corresponding two-dimensional
inner-product-space hypotheses when they need a general ambient space.

## Tags

graph drawing, graph embedding, planar graph, Kuratowski theorem
-/

open Function Set Topology
open scoped unitInterval Convex

namespace Graph

noncomputable section

variable {α β γ δ : Type*} {G H : Graph α β} {K : Graph γ δ} {e : β} {u v : α}
  {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]

/-- A drawing of `G` in `X` is a continuous injection from the weak realization of `G` to `X`. -/
structure Drawing (G : Graph α β) (X : Type*) [TopologicalSpace X] extends
    C(Realization G, X), Realization G ↪ X

-- This parent projection is generated by the `extends` command.
attribute [nolint docBlame] Drawing.toEmbedding

namespace Drawing

variable {D D' : Drawing G X}

instance : FunLike (Drawing G X) (Realization G) X where
  coe D := D.toContinuousMap
  coe_injective D₁ D₂ h := by
    cases D₁
    cases D₂
    simpa using h

instance : ContinuousMapClass (Drawing G X) (Realization G) X where
  map_continuous D := D.toContinuousMap.continuous

instance : EmbeddingLike (Drawing G X) (Realization G) X where
  injective' D := D.toEmbedding.injective

@[ext]
theorem ext {D₁ D₂ : Drawing G X} (h : ∀ x, D₁ x = D₂ x) : D₁ = D₂ :=
  DFunLike.coe_injective <| funext h

@[simp]
lemma coe_toContinuousMap (D : Drawing G X) : ⇑D.toContinuousMap = D := rfl

/-- A drawing is continuous. -/
lemma continuous (D : Drawing G X) : Continuous D :=
  D.toContinuousMap.continuous

/-- A drawing is injective. -/
lemma injective (D : Drawing G X) : Injective D :=
  D.toEmbedding.injective

/-- The point assigned by a drawing to a vertex. -/
def vertex (D : Drawing G X) (x : V(G)) : X :=
  D (vertexMk x)

/-- The path assigned by a drawing to an edge. -/
noncomputable def edgePath (D : Drawing G X) (e : E(G)) :
    Path (D.vertex (edgeSource e)) (D.vertex (edgeTarget e)) :=
  (G.edgePath e).map D.continuous

/-- The image of the realization under a drawing. -/
def support (D : Drawing G X) : Set X :=
  range D

@[simp]
lemma vertex_mem_support (D : Drawing G X) (x : V(G)) : D.vertex x ∈ D.support :=
  ⟨vertexMk x, rfl⟩

lemma edgePath_range_subset_support (D : Drawing G X) (e : E(G)) :
    range (D.edgePath e) ⊆ D.support := by
  rintro _ ⟨t, rfl⟩
  refine ⟨G.edgePath e t, rfl⟩

/-- Distinct vertices have distinct images in a drawing. -/
lemma vertex_injective (D : Drawing G X) : Injective D.vertex :=
  fun _ _ hxy ↦ vertexMk_inj.mp <| D.injective hxy

@[simp]
lemma edgePath_apply (D : Drawing G X) (e : E(G)) (t : I) : D.edgePath e t = D (G.edgePath e t) :=
  rfl

/-- Every point of the support is either a vertex image or lies on some edge path. -/
lemma support_eq (D : Drawing G X) :
    D.support = range D.vertex ∪ ⋃ e : E(G), range (D.edgePath e) := by
  ext x
  simp only [support, mem_range, mem_union, mem_iUnion]
  constructor
  · rintro ⟨y, rfl⟩
    induction y using Realization.ind with | h a =>
    match a with
    | .inl v => exact Or.inl ⟨v, rfl⟩
    | .inr ⟨e, t⟩ => exact Or.inr ⟨e, t, by simp [edgePath_apply]⟩
  · rintro (⟨v, rfl⟩ | ⟨e, t, rfl⟩)
    · exact ⟨vertexMk v, rfl⟩
    · exact ⟨G.edgePath e t, rfl⟩

/-- The open part of each edge path is injectively parametrized. -/
lemma edgePath_injOn_Ioo (D : Drawing G X) (e : E(G)) :
    InjOn (D.edgePath e) (Ioo (0 : unitInterval) 1) :=
  fun _ ht₁ _ _ heq ↦ edgePath_inj_of_mem_Ioo (mod_cast ht₁) <| D.injective heq

/-- The open part of an edge is disjoint from all vertex images. -/
lemma pathInterior_edgePath_disjoint_vertex (D : Drawing G X) (e : E(G)) :
    Disjoint (D.edgePath e).Interior (range D.vertex) := by
  refine disjoint_left.mpr ?_
  rintro _ ⟨t, ht, rfl⟩ ⟨v, hv⟩
  exact vertexMk_not_mem_edgePath_Ioo v e ⟨t, ht, D.injective hv.symm⟩

/-- The open parts of distinct edges are disjoint. -/
lemma pathInterior_edgePath_disjoint (D : Drawing G X) {e f : E(G)} (hef : e ≠ f) :
    Disjoint (D.edgePath e).Interior (D.edgePath f).Interior := by
  refine disjoint_left.mpr ?_
  rintro _ ⟨t, ht, rfl⟩ ⟨s, hs, heq⟩
  exact ((disjoint_edgePath_Ioo_iff e f).mpr hef).notMem_of_mem_left ⟨t, ht, rfl⟩
    ⟨s, hs, D.injective heq⟩

lemma range_edgePath_inter (D : Drawing G X) {e f : E(G)} (hef : e ≠ f) :
    range (D.edgePath e) ∩ range (D.edgePath f) = {D.vertex (edgeSource e),
      D.vertex (edgeTarget e)} ∩ {D.vertex (edgeSource f), D.vertex (edgeTarget f)} := by
  refine subset_antisymm ?_ (inter_subset_inter ?_ ?_)
  rotate_left
  · rintro _ (rfl | rfl) <;> simp
  · rintro _ (rfl | rfl) <;> simp
  have key {g h : E(G)} (hgh : g ≠ h) {z : X} {tg sh : I} (htg : D.edgePath g tg = z)
      (hsh : D.edgePath h sh = z) : z = D.vertex (edgeSource g) ∨ z = D.vertex (edgeTarget g) := by
    obtain rfl | rfl | htgI := (D.edgePath g).mem_range_iff_mem_interior_or_source_or_target z
      |>.mp (by simp [← htg])
    · tauto
    · tauto
    have hnotV : z ∉ range D.vertex :=
      (D.pathInterior_edgePath_disjoint_vertex g).notMem_of_mem_left htgI
    obtain rfl | rfl | hshI := unitInterval.eq_zero_or_eq_one_or_mem_Ioo sh
    · exact (hnotV ⟨edgeSource h, by rw [← hsh, Path.source]⟩).elim
    · exact (hnotV ⟨edgeTarget h, by rw [← hsh, Path.target]⟩).elim
    exact ((D.pathInterior_edgePath_disjoint hgh).notMem_of_mem_left htgI ⟨sh, hshI, hsh⟩).elim
  intro z ⟨⟨te, hte⟩, ⟨sf, hsf⟩⟩
  exact ⟨by simpa [mem_insert_iff, mem_singleton_iff] using key hef hte hsf,
    by simpa [mem_insert_iff, mem_singleton_iff] using key hef.symm hsf hte⟩

/-- The support of a drawing of a finite graph is compact. -/
lemma support_isCompact [G.Finite] (D : Drawing G X) : IsCompact D.support :=
  isCompact_range D.continuous

/-- In a Hausdorff space, the support of a drawing of a finite graph is closed. -/
lemma support_isClosed [G.Finite] [T2Space X] (D : Drawing G X) : IsClosed D.support :=
  D.support_isCompact.isClosed

/-- Postcompose a drawing with a continuous injection of ambient spaces. -/
def postcomp (D : Drawing G X) (f : C(X, Y)) (hf : Injective f) : Drawing G Y where
  toContinuousMap := f.comp D.toContinuousMap
  inj' := hf.comp D.injective

@[simp]
lemma postcomp_apply (D : Drawing G X) (f : C(X, Y)) (hf : Injective f)
    (x : Realization G) : D.postcomp f hf x = f (D x) :=
  rfl

/-! ### Constructors -/

/-- Construct a drawing from a map on the pre-realization that identifies exactly the points
identified by the realization quotient. -/
noncomputable def ofPreRealization (f : C(G.PreRealization, X))
    (map_eq_of_glueRel : ∀ a b, G.glueRel a b → f a = f b)
    (glueRel_of_map_eq : ∀ a b, f a = f b → G.glueRel a b) : Drawing G X where
  toContinuousMap :=
    ⟨Quotient.lift f map_eq_of_glueRel, continuous_quot_lift map_eq_of_glueRel f.continuous⟩
  inj' x y h := by
    induction x using Realization.ind with | h a =>
    induction y using Realization.ind with | h b =>
    exact Realization.mk_eq_mk.mpr (glueRel_of_map_eq a b h)

/-- Construct a drawing by assigning distinct points to vertices and internally disjoint paths to
edges.

The hypotheses allow loops and parallel edges. For a loop, the two endpoints of its path agree,
as prescribed by `edgeSource` and `edgeTarget`; only the open interval is required to be
injective. -/
noncomputable def preRealizationMapOfPaths (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) :
    C(G.PreRealization, X) :=
  ⟨Sum.elim vertex fun p ↦ edge p.1 p.2, continuous_sum_dom.mpr ⟨continuous_of_discreteTopology,
    continuous_sigma fun e ↦ (edge e).continuous⟩⟩

@[simp]
lemma preRealizationMapOfPaths_inl (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (x : V(G)) :
    preRealizationMapOfPaths vertex edge (Sum.inl x) = vertex x := rfl

@[simp]
lemma preRealizationMapOfPaths_inr (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (e : E(G))
    (t : unitInterval) :
    preRealizationMapOfPaths vertex edge (Sum.inr ⟨e, t⟩) = edge e t := rfl

/-- The endpoints of the paths are where the realization glues, so the map respects the relation.
This direction needs no hypothesis: it is `Path.source` and `Path.target`. -/
theorem map_eq_of_glueRel_preRealizationMapOfPaths (vertex : V(G) → X) {a b}
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (h : G.glueRel a b) :
    preRealizationMapOfPaths vertex edge a = preRealizationMapOfPaths vertex edge b := by
  induction h with
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ h₁ h₂ => exact h₁.trans h₂
  | rel x y hxy =>
    match x, y with
    | .inr _, _ => simp [glueRelAux] at hxy
    | .inl u, .inl v => rw [(glueRelAux_inl_inl_iff ..).mp hxy]
    | .inl u, .inr ⟨e, t⟩ =>
      obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := (glueRelAux_inl_inr_iff ..).mp hxy
      · simp [Path.source]
      · simp [Path.target]

/-- Conversely, the map identifies *only* what the realization glues. This is where all four
hypotheses are used, and it is the whole mathematical content of `ofVertexAndEdgePaths`. -/
theorem glueRel_of_map_eq_preRealizationMapOfPaths {a b} (vertex : V(G) → X)
    (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (edge e).Interior (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f → Disjoint (edge e).Interior (edge f).Interior)
    (h : preRealizationMapOfPaths vertex edge a = preRealizationMapOfPaths vertex edge b) :
    G.glueRel a b := by
  match a, b with
  | .inl u, .inl v => exact (glueRel_inl_inl_iff u v).mpr (vertex_injective (by simpa using h))
  | .inl u, .inr ⟨e, t⟩ =>
    have hvt : vertex u = edge e t := by simpa using h
    obtain rfl | ht0 := eq_or_ne t 0
    · exact (glueRel_inl_inr_iff u e 0).mpr <|
        .inl ⟨rfl, vertex_injective (by rwa [Path.source] at hvt)⟩
    rcases eq_or_ne t 1 with rfl | ht1
    · exact (glueRel_inl_inr_iff u e 1).mpr <|
        .inr ⟨rfl, vertex_injective (by simpa [Path.target] using hvt)⟩
    · exact ((edge_interior_disjoint_vertex e).notMem_of_mem_left
        ⟨t, ⟨unitInterval.pos_iff_ne_zero.mpr ht0, unitInterval.lt_one_iff_ne_one.mpr ht1⟩, rfl⟩
        ⟨u, hvt⟩).elim
  | .inr ⟨e, t⟩, .inl v =>
    have hvt : edge e t = vertex v := by simpa using h
    rcases eq_or_ne t 0 with rfl | ht0
    · exact (glueRel_inr_inl_iff e 0 v).mpr <|
        .inl ⟨rfl, vertex_injective (by simpa [Path.source] using hvt.symm)⟩
    rcases eq_or_ne t 1 with rfl | ht1
    · exact (glueRel_inr_inl_iff e 1 v).mpr <|
        .inr ⟨rfl, vertex_injective (by simpa [Path.target] using hvt.symm)⟩
    · exact ((edge_interior_disjoint_vertex e).notMem_of_mem_left
        ⟨t, ⟨unitInterval.pos_iff_ne_zero.mpr ht0, unitInterval.lt_one_iff_ne_one.mpr ht1⟩, rfl⟩
        ⟨v, hvt.symm⟩).elim
  | .inr ⟨e₁, t₁⟩, .inr ⟨e₂, t₂⟩ =>
    have heq : edge e₁ t₁ = edge e₂ t₂ := by simpa using h
    rcases eq_or_ne t₁ 0 with rfl | ht₁₀
    · rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · have hv : edgeSource e₁ = edgeSource e₂ :=
          vertex_injective (by simpa [Path.source] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 0 0).mpr <| Or.inr ⟨edgeSource e₁, by simp, ?_⟩
        simp [hv]
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · have hv : edgeSource e₁ = edgeTarget e₂ :=
          vertex_injective (by simpa [Path.source, Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 0 1).mpr <| Or.inr ⟨edgeSource e₁, by simp, ?_⟩
        simp [hv]
      · exact ((edge_interior_disjoint_vertex e₂).notMem_of_mem_left ⟨t₂,
          ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩, rfl⟩
          ⟨edgeSource e₁, by simpa [Path.source] using heq⟩).elim
    rcases eq_or_ne t₁ 1 with rfl | ht₁₁
    · rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · have hv : edgeTarget e₁ = edgeSource e₂ :=
          vertex_injective (by simpa [Path.source, Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 1 0).mpr <| Or.inr ⟨edgeTarget e₁, by simp, ?_⟩
        simp [hv]
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · have hv : edgeTarget e₁ = edgeTarget e₂ :=
          vertex_injective (by simpa [Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 1 1).mpr <| Or.inr ⟨edgeTarget e₁, by simp, ?_⟩
        simp [hv]
      · exact ((edge_interior_disjoint_vertex e₂).notMem_of_mem_left ⟨t₂,
          ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩, rfl⟩
          ⟨edgeTarget e₁, by simpa [Path.target] using heq⟩).elim
    · have ht₁ : t₁ ∈ Ioo (0 : I) 1 :=
        ⟨unitInterval.pos_iff_ne_zero.mpr ht₁₀, unitInterval.lt_one_iff_ne_one.mpr ht₁₁⟩
      rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · exact ((edge_interior_disjoint_vertex e₁).notMem_of_mem_left ⟨t₁, ht₁, rfl⟩
          ⟨edgeSource e₂, by simpa [Path.source] using heq.symm⟩).elim
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · exact ((edge_interior_disjoint_vertex e₁).notMem_of_mem_left ⟨t₁, ht₁, rfl⟩
          ⟨edgeTarget e₂, by simpa [Path.target] using heq.symm⟩).elim
      · have ht₂ : t₂ ∈ Ioo (0 : I) 1 :=
          ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩
        obtain rfl | he := eq_or_ne e₁ e₂
        · exact (glueRel_inr_inr_iff e₁ e₁ t₁ t₂).mpr <|
            Or.inl ⟨rfl, edge_injective e₁ ht₁ ht₂ heq⟩
        · exact ((edge_interior_disjoint e₁ e₂ he).notMem_of_mem_left
            ⟨t₁, ht₁, rfl⟩ ⟨t₂, ht₂, heq.symm⟩).elim

noncomputable def ofVertexAndEdgePaths
    (vertex : V(G) → X) (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (edge e).Interior (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f → Disjoint (edge e).Interior (edge f).Interior) :
    Drawing G X :=
  ofPreRealization (preRealizationMapOfPaths vertex edge)
    (fun _ _ ↦ map_eq_of_glueRel_preRealizationMapOfPaths vertex edge)
    (fun _ _ ↦ glueRel_of_map_eq_preRealizationMapOfPaths vertex vertex_injective edge
      edge_injective edge_interior_disjoint_vertex edge_interior_disjoint)

variable {vertex : V(G) → X} {edge : ∀ e : E(G), Path (vertex (edgeSource e))
  (vertex (edgeTarget e))} {hv : Injective vertex} {he : ∀ e, InjOn (edge e) (Ioo (0 : I) 1)}
  {hev : ∀ e, Disjoint (edge e).Interior (range vertex)}
  {hee : ∀ e f, e ≠ f → Disjoint (edge e).Interior (edge f).Interior}

@[simp]
lemma ofVertexAndEdgePaths_vertex (x : V(G)) :
    (ofVertexAndEdgePaths vertex hv edge he hev hee).vertex x = vertex x := rfl

@[simp]
lemma ofVertexAndEdgePaths_edgePath_apply (e : E(G)) (t : unitInterval) :
    (ofVertexAndEdgePaths vertex hv edge he hev hee).edgePath e t = edge e t := rfl

lemma range_edgePath_ofVertexAndEdgePaths (e : E(G)) :
    range ((ofVertexAndEdgePaths vertex hv edge he hev hee).edgePath e) = range (edge e) := rfl

/-- The empty graph has a drawing in every topological space, including the empty space. -/
noncomputable def bot (X : Type*) [TopologicalSpace X] : Drawing (⊥ : Graph α β) X :=
  ofPreRealization ⟨fun a ↦ isEmptyElim a, continuous_of_discreteTopology⟩
    (fun a ↦ isEmptyElim a) (fun a ↦ isEmptyElim a)

/-! ### Restriction and transport -/

/-- Restrict a drawing to a subgraph. -/
def restrict (D : Drawing G X) (h : H ≤ G) : Drawing H X where
  toContinuousMap := D.toContinuousMap.comp h.realizationContinuousMap
  inj' := D.injective.comp h.RealizationEmbedding_isEmbedding.injective

@[simp]
lemma restrict_apply (D : Drawing G X) (h : H ≤ G) (x : Realization H) :
    D.restrict h x = D (h.RealizationEmbedding x) := rfl

/-! Restriction changes neither the position of a vertex nor the image of an edge. The two
`edgeSource`/`edgeTarget` statements are the ones that would fail if the orientation of an edge
were chosen per graph rather than determined by its ends; they hold because `ArbRel` fixes one
linear order per *type*, so `IsSubgraph.source` and `IsSubgraph.target` are available. -/

@[simp]
lemma restrict_vertex (D : Drawing G X) (h : H ≤ G) (x : V(H)) :
    (D.restrict h).vertex x = D.vertex ⟨x.1, vertexSet_mono h x.2⟩ := by
  simp [vertex, restrict_apply]

lemma restrict_vertex_edgeSource (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    (D.restrict h).vertex (edgeSource e) = D.vertex (edgeSource ⟨e.1, edgeSet_mono h e.2⟩) := by
  rw [restrict_vertex]
  congr 1
  ext
  simp [edgeSource, h.source]

lemma restrict_vertex_edgeTarget (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    (D.restrict h).vertex (edgeTarget e) = D.vertex (edgeTarget ⟨e.1, edgeSet_mono h e.2⟩) := by
  rw [restrict_vertex]
  congr 1
  ext
  simp [edgeTarget, h.target]

@[simp]
lemma range_edgePath_restrict (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    range ((D.restrict h).edgePath e) = range (D.edgePath ⟨e.1, edgeSet_mono h e.2⟩) := by
  ext x
  simp only [mem_range]
  refine ⟨fun ⟨t, ht⟩ ↦ ⟨t, ?_⟩, fun ⟨t, ht⟩ ↦ ⟨t, ?_⟩⟩ <;>
    rw [← ht, edgePath_apply, edgePath_apply, restrict_apply, h.RealizationEmbedding_edgePath]

/-- Pull a drawing back along a graph isomorphism. -/
noncomputable def ofIso (D : Drawing G X) (F : Iso K G) : Drawing K X where
  toContinuousMap :=
    ⟨D ∘ F.realizationHomeomorph, D.continuous.comp F.realizationHomeomorph.continuous⟩
  inj' := D.injective.comp F.realizationHomeomorph.injective

/-- A drawing `D'` extends `D` along the subgraph inclusion `h`. -/
def Extends (D' : Drawing G X) (D : Drawing H X) (h : H ≤ G) : Prop :=
  ∀ x, D' (h.RealizationEmbedding x) = D x

/-! ### Drawability and planarity -/

end Drawing

/-- A graph is drawable in `X` if its weak realization admits a continuous injection into `X`. -/
def IsDrawable (G : Graph α β) (X : Type*) [TopologicalSpace X] : Prop :=
  Nonempty (Drawing G X)

/-- A graph is planar if it has a drawing in the Euclidean plane. -/
def Planar (G : Graph α β) : Prop :=
  G.IsDrawable (EuclideanSpace ℝ (Fin 2))

/-- The empty graph is drawable in every topological space. -/
theorem bot_isDrawable (X : Type*) [TopologicalSpace X] :
    (⊥ : Graph α β).IsDrawable X :=
  ⟨Drawing.bot X⟩

/-- The empty graph is planar. -/
theorem bot_planar : (⊥ : Graph α β).Planar :=
  bot_isDrawable (EuclideanSpace ℝ (Fin 2))

namespace IsDrawable

/-- Drawability is inherited by subgraphs. -/
lemma anti (hG : G.IsDrawable X) (hHG : H ≤ G) : H.IsDrawable X :=
  ⟨hG.some.restrict hHG⟩

/-- Drawability is invariant under graph isomorphism. -/
lemma of_iso (hG : G.IsDrawable X) (F : Iso K G) : K.IsDrawable X :=
  ⟨hG.some.ofIso F⟩

end IsDrawable

namespace Planar

/-- Planarity is inherited by subgraphs. -/
lemma anti (hG : G.Planar) (hHG : H ≤ G) : H.Planar :=
  IsDrawable.anti hG hHG

/-- Planarity is invariant under graph isomorphism. -/
lemma of_iso (hG : G.Planar) (F : Iso K G) : K.Planar :=
  IsDrawable.of_iso hG F

/- Topological-minor and subdivision transport are in `Planarity.TopologicalMinor`; keeping them
out of this basic file avoids imposing that API on every use of drawings. -/

end Planar

abbrev Plane := EuclideanSpace ℝ (Fin 2)

/-- Embed a finite type into the plane along the x-axis. -/
noncomputable def embedFinite (ι : Type*) [Finite ι] : ι → Plane :=
  fun i => EuclideanSpace.single 0 (Finite.equivFin ι i : ℝ)

lemma embedFinite_injective (ι : Type*) [Finite ι] : Injective (embedFinite ι) := by
  intro a b h
  have : (Finite.equivFin ι a : ℝ) = (Finite.equivFin ι b : ℝ) := by
    simpa [embedFinite, PiLp.single_apply] using congrArg (fun v : Plane => v 0) h
  exact (Finite.equivFin ι).injective (Fin.val_injective (Nat.cast_injective this))

lemma Path.interior_segment (a b : Plane) :
    (Path.segment a b).Interior = openSegment ℝ a b := by
  ext z
  constructor
  · rintro ⟨t, ht, rfl⟩
    rw [openSegment_eq_image_lineMap]
    exact ⟨t, ht, by simp [Path.segment_apply]⟩
  · rw [openSegment_eq_image_lineMap]
    rintro ⟨t, ht, rfl⟩
    exact ⟨⟨t, ht.1.le, ht.2.le⟩, ht, by simp [Path.segment_apply]⟩

/-- An edgeless finite graph is planar. -/
theorem noEdge_planar (V : Set α) (hV : V.Finite) : (Graph.noEdge V β).Planar := by
  have : (Graph.noEdge V β).Finite := (noEdge_finite V).mpr hV
  have : Finite ↑V(Graph.noEdge V β) := by
    simpa [vertexSet_noEdge] using hV.to_subtype
  refine ⟨Drawing.ofVertexAndEdgePaths (embedFinite _) (embedFinite_injective _)
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed _ _ => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))⟩

lemma singleEdge_edgeSource_ne_edgeTarget {x y : α} (hxy : x ≠ y) (e : β)
    (f : E(Graph.singleEdge x y e)) : edgeSource f ≠ edgeTarget f := by
  intro heq
  have hlink := isLink_edgeSource_edgeTarget f
  have hf : (f : β) = e := by simpa [edgeSet_singleEdge] using f.2
  have heq' : (edgeSource f : α) = edgeTarget f := congrArg Subtype.val heq
  rw [singleEdge_isLink_iff, hf, heq'] at hlink
  obtain ⟨-, hs⟩ := hlink
  obtain ⟨h1, h2⟩ | ⟨h1, h2⟩ := Sym2.eq_iff.mp hs
  · exact hxy (h1.symm.trans h2)
  · exact hxy (h2.symm.trans h1)

/-- A nonloop edge is planar. -/
theorem singleEdge_planar {x y : α} (hxy : x ≠ y) (e : β) : (Graph.singleEdge x y e).Planar := by
  set G := Graph.singleEdge x y e
  have : Finite ↑V(G) := by
    change Finite ↑({x, y} : Set α)
    infer_instance
  let e' : E(G) := ⟨e, by simp [G]⟩
  set vertex : V(G) → Plane := embedFinite V(G)
  have hv : Injective vertex := embedFinite_injective _
  have he : ∀ f : E(G), f = ⟨e, by simp [G]⟩ := by simp [G]
  have hne : ∀ f : E(G), edgeSource f ≠ edgeTarget f :=
    fun f ↦ singleEdge_edgeSource_ne_edgeTarget hxy e f
  set edge : ∀ f : E(G), Path (vertex (edgeSource f)) (vertex (edgeTarget f)) :=
    fun f => Path.segment (vertex (edgeSource f)) (vertex (edgeTarget f))
  refine ⟨Drawing.ofVertexAndEdgePaths vertex hv edge (fun f _ _ _ _ heq ↦
    Path.segment_injective_of_ne (hv.ne (hne f)) heq) (fun f ↦ disjoint_left.mpr ?_)
    fun f g hfg ↦ by grind⟩
  obtain rfl := he f
  rintro z ⟨t, ht, rfl⟩ ⟨v, hvz⟩
  have hzopen : edge e' t ∈ openSegment ℝ (vertex (edgeSource e')) (vertex (edgeTarget e')) := by
    simpa [← Path.interior_segment] using ⟨t, ht, rfl⟩
  have hlink : s((edgeSource e' : α), (edgeTarget e' : α)) = s(x, y) := by
    rw [← isLink_edgeSource_edgeTarget e' |>.isLink_iff_sym2_eq]
    simp only [singleEdge_isLink, and_self, true_or, G, e']
  have hvxy : (v : α) = x ∨ (v : α) = y := by
    simpa [G, vertexSet_singleEdge] using v.2
  obtain hmap | hmap : vertex v = vertex (edgeSource e') ∨ vertex v = vertex (edgeTarget e') := by
    obtain ⟨hs, ht⟩ | ⟨hs, ht⟩ := Sym2.eq_iff.mp hlink <;> obtain hvx | hvy := hvxy
    · exact Or.inl (congrArg vertex (Subtype.ext (hvx.trans hs.symm)))
    · exact Or.inr (congrArg vertex (Subtype.ext (hvy.trans ht.symm)))
    · exact Or.inr (congrArg vertex (Subtype.ext (hvx.trans ht.symm)))
    · exact Or.inl (congrArg vertex (Subtype.ext (hvy.trans hs.symm)))
  · exact hv.ne (hne e') (left_mem_openSegment_iff.mp (by rwa [← hvz, hmap] at hzopen))
  · exact hv.ne (hne e') (right_mem_openSegment_iff.mp (by rwa [← hvz, hmap] at hzopen))

/-! ### Straight-line drawing on at most four vertices -/

private def toPlane (x y : ℝ) : Plane := (WithLp.equiv 2 (Fin 2 → ℝ)).symm ![x, y]

@[simp] private lemma toPlane_zero (x y : ℝ) : toPlane x y 0 = x := by simp [toPlane]
@[simp] private lemma toPlane_one (x y : ℝ) : toPlane x y 1 = y := by simp [toPlane]

/-- Four plane points realizing a triangle with an interior vertex: `(0,0)`, `(2,0)`, `(0,2)`,
`(1,1/2)`. -/
private def pts4 : Fin 4 → Plane :=
  ![toPlane 0 0, toPlane 2 0, toPlane 0 2, toPlane 1 (1 / 2)]

private lemma pts4_injective : Injective pts4 := by
  intro a b h
  have hx := congrArg (fun v : Plane => v 0) h
  have hy := congrArg (fun v : Plane => v 1) h
  fin_cases a <;> fin_cases b <;> simp [pts4] at hx hy ⊢

private lemma linInd_of_det {u v : Plane} (h : u 0 * v 1 - u 1 * v 0 ≠ 0) :
    LinearIndependent ℝ ![u, v] := by
  rw [linearIndependent_fin2]
  refine ⟨?_, fun a ha => ?_⟩
  · intro hv
    exact h (by
      have hv0 : v 0 = 0 := by simpa using congrArg (fun w : Plane => w 0) hv
      have hv1 : v 1 = 0 := by simpa using congrArg (fun w : Plane => w 1) hv
      simp [hv0, hv1])
  · have h0 := congrArg (fun w : Plane => w 0) ha
    have h1 := congrArg (fun w : Plane => w 1) ha
    simp [PiLp.smul_apply] at h0 h1
    refine h ?_
    calc
      u 0 * v 1 - u 1 * v 0
          = (a * v 0) * v 1 - (a * v 1) * v 0 := by rw [← h0, ← h1]
        _ = 0 := by ring

private lemma det_pts4_star {c x y : Fin 4} (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    (pts4 x - pts4 c) 0 * (pts4 y - pts4 c) 1 -
      (pts4 x - pts4 c) 1 * (pts4 y - pts4 c) 0 ≠ 0 := by
  fin_cases c <;> fin_cases x <;> fin_cases y <;>
    simp_all [pts4, PiLp.sub_apply] <;> norm_num

private lemma linearIndependent_pts4_star {c x y : Fin 4}
    (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    LinearIndependent ℝ ![pts4 x - pts4 c, pts4 y - pts4 c] :=
  linInd_of_det (det_pts4_star hx hy hxy)

private lemma openSegment_star_disjoint {c x y : Fin 4}
    (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    Disjoint (openSegment ℝ (pts4 c) (pts4 x)) (openSegment ℝ (pts4 c) (pts4 y)) := by
  refine disjoint_left.2 fun p hpx hpy => ?_
  have hinter : p ∈ segment ℝ (pts4 c) (pts4 x) ∩ segment ℝ (pts4 c) (pts4 y) :=
    ⟨openSegment_subset_segment _ _ _ hpx, openSegment_subset_segment _ _ _ hpy⟩
  have hp : p = pts4 c := by
    have := segment_inter_eq_endpoint_of_linearIndependent_sub ℝ
      (linearIndependent_pts4_star hx hy hxy)
    simpa [this] using hinter
  have : pts4 c = pts4 x := (left_mem_openSegment_iff (y := pts4 x)).mp (by rwa [hp] at hpx)
  exact hx (pts4_injective this.symm)

private lemma not_mem_openSegment_pts4 {i j k : Fin 4}
    (hij : i ≠ j) (hik : k ≠ i) (hjk : k ≠ j) :
    pts4 k ∉ openSegment ℝ (pts4 i) (pts4 j) := by
  intro h
  rw [openSegment_eq_image'] at h
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := h
  have hx := congrArg (fun v : Plane => v 0) heq
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx hy
  fin_cases i <;> fin_cases j <;> fin_cases k <;>
    simp_all [pts4] <;> (try linarith)

private lemma openSegment_eq_of_sym2 {a b c d : Fin 4} (h : s(a, b) = s(c, d)) :
    openSegment ℝ (pts4 a) (pts4 b) = openSegment ℝ (pts4 c) (pts4 d) := by
  rcases (Sym2.eq_iff).mp h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · rfl
  · exact openSegment_symm _ _ _

private lemma openSegment_01_23 :
    Disjoint (openSegment ℝ (pts4 0) (pts4 1)) (openSegment ℝ (pts4 2) (pts4 3)) := by
  refine disjoint_left.2 fun p hp01 hp23 => ?_
  rw [openSegment_eq_image'] at hp01 hp23
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp01
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp23
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hy
  have : t = 4 / 3 := by ring_nf at hy; linarith
  linarith

private lemma openSegment_02_13 :
    Disjoint (openSegment ℝ (pts4 0) (pts4 2)) (openSegment ℝ (pts4 1) (pts4 3)) := by
  refine disjoint_left.2 fun p hp01 hp23 => ?_
  rw [openSegment_eq_image'] at hp01 hp23
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp01
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp23
  have hx := congrArg (fun v : Plane => v 0) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx
  have : t = 2 := by linarith
  linarith

private lemma openSegment_12_03 :
    Disjoint (openSegment ℝ (pts4 1) (pts4 2)) (openSegment ℝ (pts4 0) (pts4 3)) := by
  refine disjoint_left.2 fun p hp12 hp03 => ?_
  rw [openSegment_eq_image'] at hp12 hp03
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp12
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp03
  have hx := congrArg (fun v : Plane => v 0) heq
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx hy
  have hs : s = 1 / 3 := by
    have ht : t = 2 - 2 * s := by linarith
    have : 2 * s = t / 2 := by linarith
    rw [ht] at this; linarith
  have : t = 4 / 3 := by linarith
  linarith

private lemma exists_canon_edge {a b : Fin 4} (hab : a ≠ b) :
    ∃ u v : Fin 4, u < v ∧ s(a, b) = s(u, v) := by
  wlog hlt : a < b generalizing a b
  · obtain ⟨u, v, huv, heq⟩ := this hab.symm (lt_of_le_of_ne (le_of_not_gt hlt) hab.symm)
    exact ⟨u, v, huv, by simpa [Sym2.eq_swap] using heq⟩
  exact ⟨a, b, hlt, rfl⟩

private lemma openSegment_pts4_disjoint_complementary {u v u' v' : Fin 4}
    (huv : u < v) (huv' : u' < v') (hne : s(u, v) ≠ s(u', v'))
    (hdisj : Disjoint ({u, v} : Set (Fin 4)) {u', v'}) :
    Disjoint (openSegment ℝ (pts4 u) (pts4 v)) (openSegment ℝ (pts4 u') (pts4 v')) := by
  fin_cases u <;> fin_cases v <;> fin_cases u' <;> fin_cases v' <;>
    simp_all [Fin.lt_def] <;>
    first
    | exact openSegment_01_23
    | exact openSegment_02_13
    | exact openSegment_12_03
    | exact openSegment_01_23.symm
    | exact openSegment_02_13.symm
    | exact openSegment_12_03.symm

private lemma openSegment_pts4_disjoint {i j k ℓ : Fin 4}
    (hij : i ≠ j) (hkl : k ≠ ℓ) (hne : s(i, j) ≠ s(k, ℓ)) :
    Disjoint (openSegment ℝ (pts4 i) (pts4 j)) (openSegment ℝ (pts4 k) (pts4 ℓ)) := by
  obtain ⟨u, v, huv, heq1⟩ := exists_canon_edge hij
  obtain ⟨u', v', huv', heq2⟩ := exists_canon_edge hkl
  have hne' : s(u, v) ≠ s(u', v') := fun h => hne (heq1.trans (h.trans heq2.symm))
  rw [openSegment_eq_of_sym2 heq1, openSegment_eq_of_sym2 heq2]
  by_cases hshare : ({u, v} ∩ {u', v'} : Set (Fin 4)).Nonempty
  · obtain ⟨c, hc⟩ := hshare
    have hc1 : c ∈ ({u, v} : Set _) := hc.1
    have hc2 : c ∈ ({u', v'} : Set _) := hc.2
    let x : Fin 4 := if c = u then v else u
    let y : Fin 4 := if c = u' then v' else u'
    have hx : x ≠ c := by
      dsimp [x]; split_ifs with hcu
      · exact hcu ▸ huv.ne'
      · have : c = v := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc1
          exact hc1.resolve_left hcu
        exact this ▸ huv.ne
    have hy : y ≠ c := by
      dsimp [y]; split_ifs with hcu
      · exact hcu ▸ huv'.ne'
      · have : c = v' := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc2
          exact hc2.resolve_left hcu
        exact this ▸ huv'.ne
    have hxy : x ≠ y := by
      intro heqxy
      apply hne'
      have e1 : s(u, v) = s(c, x) := by
        dsimp [x]; split_ifs with hcu
        · subst hcu; rfl
        · have : c = v := by
            simp only [mem_insert_iff, mem_singleton_iff] at hc1
            exact hc1.resolve_left hcu
          subst this; exact Sym2.eq_swap
      have e2 : s(u', v') = s(c, y) := by
        dsimp [y]; split_ifs with hcu
        · subst hcu; rfl
        · have : c = v' := by
            simp only [mem_insert_iff, mem_singleton_iff] at hc2
            exact hc2.resolve_left hcu
          subst this; exact Sym2.eq_swap
      exact e1.trans (heqxy ▸ e2.symm)
    have e1 : openSegment ℝ (pts4 u) (pts4 v) = openSegment ℝ (pts4 c) (pts4 x) := by
      dsimp [x]; split_ifs with hcu
      · subst hcu; rfl
      · have : c = v := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc1
          exact hc1.resolve_left hcu
        subst this; exact openSegment_symm _ _ _
    have e2 : openSegment ℝ (pts4 u') (pts4 v') = openSegment ℝ (pts4 c) (pts4 y) := by
      dsimp [y]; split_ifs with hcu
      · subst hcu; rfl
      · have : c = v' := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc2
          exact hc2.resolve_left hcu
        subst this; exact openSegment_symm _ _ _
    rw [e1, e2]
    exact openSegment_star_disjoint hx hy hxy
  · push Not at hshare
    have hdisj : Disjoint ({u, v} : Set (Fin 4)) {u', v'} := by
      rw [disjoint_iff_inter_eq_empty]; simpa using hshare
    exact openSegment_pts4_disjoint_complementary huv huv' hne' hdisj

/-- Every finite simple graph on at most four vertices is planar.

This is proved by a straight-line drawing with vertices at
`(0,0)`, `(2,0)`, `(0,2)`, `(1,1/2)` (triangle plus interior point) and edges as segments,
fed to `Drawing.ofVertexAndEdgePaths`. -/
theorem planar_of_vertexSet_encard_le_four [G.Finite] [G.Simple]
    (hG : V(G).encard ≤ 4) : G.Planar := by
  have : Fintype V(G) := Fintype.ofFinite _
  have hcard : Fintype.card V(G) ≤ 4 := by
    have heq : V(G).encard = (Fintype.card V(G) : ℕ∞) := by
      rw [Set.encard_eq_coe_toFinset_card, Set.toFinset_card]
    have : ((Fintype.card V(G) : ℕ) : ℕ∞) ≤ 4 := by rwa [← heq]
    exact Nat.cast_le.mp this
  let ι : V(G) ↪ Fin 4 :=
    (Fintype.equivFin V(G)).toEmbedding.trans (Fin.castLEEmb hcard)
  set vertex : V(G) → Plane := pts4 ∘ ι
  have hv : Injective vertex := pts4_injective.comp ι.injective
  have hne : ∀ e : E(G), edgeSource e ≠ edgeTarget e := by
    intro e heq
    exact (isLink_edgeSource_edgeTarget e).ne (congrArg Subtype.val heq)
  set edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)) :=
    fun e => Path.segment (vertex (edgeSource e)) (vertex (edgeTarget e))
  refine ⟨Drawing.ofVertexAndEdgePaths vertex hv edge ?_ ?_ ?_⟩
  · intro e _ _ _ _ heq
    exact Path.segment_injective_of_ne (hv.ne (hne e)) heq
  · intro e
    rw [Path.interior_segment]
    refine disjoint_left.mpr ?_
    rintro z hz ⟨w, rfl⟩
    have hij : ι (edgeSource e) ≠ ι (edgeTarget e) := ι.injective.ne (hne e)
    have hz' : pts4 (ι w) ∈
        openSegment ℝ (pts4 (ι (edgeSource e))) (pts4 (ι (edgeTarget e))) := by
      simpa [vertex] using hz
    by_cases h1 : ι w = ι (edgeSource e)
    · rw [h1] at hz'
      exact hij (pts4_injective (left_mem_openSegment_iff.mp hz'))
    · by_cases h2 : ι w = ι (edgeTarget e)
      · rw [h2] at hz'
        exact hij (pts4_injective (right_mem_openSegment_iff.mp hz'))
      · exact not_mem_openSegment_pts4 hij h1 h2 hz'
  · intro e f hef
    rw [Path.interior_segment, Path.interior_segment]
    have hij : ι (edgeSource e) ≠ ι (edgeTarget e) := ι.injective.ne (hne e)
    have hkl : ι (edgeSource f) ≠ ι (edgeTarget f) := ι.injective.ne (hne f)
    have hends : G.ends e ≠ G.ends f := (ends_injective G).ne hef
    have hne_sym : s(ι (edgeSource e), ι (edgeTarget e)) ≠
        s(ι (edgeSource f), ι (edgeTarget f)) := by
      intro heq
      apply hends
      have he : G.ends e = s(edgeSource e, edgeTarget e) :=
        (isLink_edgeSource_edgeTarget e).ends_eq
      have hf : G.ends f = s(edgeSource f, edgeTarget f) :=
        (isLink_edgeSource_edgeTarget f).ends_eq
      refine (Sym2.map.injective ι.injective) ?_
      simpa [he, hf, Sym2.map_mk] using heq
    simpa [vertex] using openSegment_pts4_disjoint hij hkl hne_sym

end

end Graph
