import Matroid.Graph.Degree.Max
import Matroid.Graph.Minor.Defs
import Matroid.Graph.Planarity.Realization.Subgraph
import Matroid.Graph.TopologicalMinor
import Mathlib.Analysis.Convex.PathConnected
import Mathlib.LinearAlgebra.LinearIndependent.Basic


/-!
# Drawings of graphs

This file defines a drawing of a graph in an arbitrary topological space to be a continuous
injection from the weak realization of the graph. It also records the construction and transport
statements needed for the topological formulation of Kuratowski's theorem.

The plane-specific part of the API is deliberately small. The difficult local topology used to
split a contracted vertex is hidden behind
`Graph.Drawing.planar_of_contract_of_facial_cycle_two_paths`.

## Main definitions

- `Graph.Drawing`: a continuous injection from the weak realization of a graph.
- `Graph.IsDrawable`: existence of a drawing in a specified topological space.
- `Graph.Planar`: existence of a drawing in the Euclidean plane.
- `Graph.Drawing.Face`: a connected component of the complement of a drawing.
- `Graph.Drawing.IsFacialSubgraph`: a subgraph whose drawing is the frontier of a face.

## Main statements

- `Graph.Drawing.ofVertexAndEdgePaths`: construct a drawing from pairwise internally disjoint edge
  paths.
- `Graph.Drawing.restrict`: restrict a drawing to a subgraph.
- `Graph.Drawing.exists_facial_cycle_of_delete_vertex`: deleting a vertex of a 3-connected plane
  drawing exposes its neighbors on a facial cycle.
- `Graph.Drawing.planar_of_contract_of_facial_cycle_two_paths`: split a contracted vertex when
  the two sets of neighbors occur on two sides of a facial cycle.
- `Graph.Planar.isTopologicalMinor`: planarity is inherited by topological minors.

## Implementation notes

`Graph.Drawing` contains only continuity and injectivity. Compactness, separation, simplicity, and
finiteness are not part of the definition.

## Tags

graph drawing, graph embedding, planar graph, Kuratowski theorem
-/

open Function Set Topology
open scoped unitInterval Convex

namespace Graph

noncomputable section

universe u v w

variable {α β γ δ : Type*} {G H : Graph α β} {K : Graph γ δ} {e : β} {u v : α}
variable {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]

/-- A drawing of `G` in `X` is a continuous injection from the weak realization of `G` to `X`. -/
structure Drawing (G : Graph α β) (X : Type u) [TopologicalSpace X] extends
    C(Realization G, X), Realization G ↪ X

-- This parent projection is generated by the `extends` command.
attribute [nolint docBlame] Drawing.toEmbedding

namespace Drawing

variable {D D' : Drawing G X}

instance : FunLike (Drawing G X) (Realization G) X where
  coe D := D.toContinuousMap
  coe_injective D₁ D₂ h := by
    cases D₁
    cases D₂
    simpa using h

instance : ContinuousMapClass (Drawing G X) (Realization G) X where
  map_continuous D := D.toContinuousMap.continuous

instance : EmbeddingLike (Drawing G X) (Realization G) X where
  injective' D := D.toEmbedding.injective

@[ext]
theorem ext {D₁ D₂ : Drawing G X} (h : ∀ x, D₁ x = D₂ x) : D₁ = D₂ :=
  DFunLike.coe_injective <| funext h

@[simp]
lemma coe_toContinuousMap (D : Drawing G X) : ⇑D.toContinuousMap = D := rfl

/-- A drawing is continuous. -/
lemma continuous (D : Drawing G X) : Continuous D :=
  D.toContinuousMap.continuous

/-- A drawing is injective. -/
lemma injective (D : Drawing G X) : Injective D :=
  D.toEmbedding.injective

/-- The point assigned by a drawing to a vertex. -/
def vertex (D : Drawing G X) (x : V(G)) : X :=
  D (vertexMk x)

/-- The path assigned by a drawing to an edge. -/
noncomputable def edgePath (D : Drawing G X) (e : E(G)) :
    Path (D.vertex (edgeSource e)) (D.vertex (edgeTarget e)) :=
  (G.edgePath e).map D.continuous

/-- The image of the realization under a drawing. -/
def support (D : Drawing G X) : Set X :=
  range D

@[simp]
lemma vertex_mem_support (D : Drawing G X) (x : V(G)) : D.vertex x ∈ D.support :=
  ⟨vertexMk x, rfl⟩

lemma edgePath_range_subset_support (D : Drawing G X) (e : E(G)) :
    range (D.edgePath e) ⊆ D.support := by
  rintro _ ⟨t, rfl⟩
  refine ⟨G.edgePath e t, rfl⟩

/-- Distinct vertices have distinct images in a drawing. -/
lemma vertex_injective (D : Drawing G X) : Injective D.vertex :=
  fun _ _ hxy ↦ vertexMk_inj.mp <| D.injective hxy

@[simp]
lemma edgePath_apply (D : Drawing G X) (e : E(G)) (t : I) : D.edgePath e t = D (G.edgePath e t) :=
  rfl

/-- Every point of the support is either a vertex image or lies on some edge path. -/
lemma support_eq (D : Drawing G X) :
    D.support = range D.vertex ∪ ⋃ e : E(G), range (D.edgePath e) := by
  ext x
  simp only [support, mem_range, mem_union, mem_iUnion]
  constructor
  · rintro ⟨y, rfl⟩
    induction y using Realization.ind with | h a =>
    match a with
    | .inl v => exact Or.inl ⟨v, rfl⟩
    | .inr ⟨e, t⟩ => exact Or.inr ⟨e, t, by simp [edgePath_apply]⟩
  · rintro (⟨v, rfl⟩ | ⟨e, t, rfl⟩)
    · exact ⟨vertexMk v, rfl⟩
    · exact ⟨G.edgePath e t, rfl⟩

/-- The open part of each edge path is injectively parametrized. -/
lemma edgePath_injOn_Ioo (D : Drawing G X) (e : E(G)) :
    InjOn (D.edgePath e) (Ioo (0 : unitInterval) 1) :=
  fun _ ht₁ _ _ heq ↦ edgePath_inj_of_mem_Ioo (mod_cast ht₁) <| D.injective heq

/-- The open part of an edge is disjoint from all vertex images. -/
lemma pathInterior_edgePath_disjoint_vertex (D : Drawing G X) (e : E(G)) :
    Disjoint (D.edgePath e).Interior (range D.vertex) := by
  refine disjoint_left.mpr ?_
  rintro _ ⟨t, ht, rfl⟩ ⟨v, hv⟩
  exact vertexMk_not_mem_edgePath_Ioo v e ⟨t, ht, D.injective hv.symm⟩

/-- The open parts of distinct edges are disjoint. -/
lemma pathInterior_edgePath_disjoint (D : Drawing G X) {e f : E(G)} (hef : e ≠ f) :
    Disjoint (D.edgePath e).Interior (D.edgePath f).Interior := by
  refine disjoint_left.mpr ?_
  rintro _ ⟨t, ht, rfl⟩ ⟨s, hs, heq⟩
  exact ((disjoint_edgePath_Ioo_iff e f).mpr hef).notMem_of_mem_left ⟨t, ht, rfl⟩
    ⟨s, hs, D.injective heq⟩

lemma range_edgePath_inter (D : Drawing G X) {e f : E(G)} (hef : e ≠ f) :
    range (D.edgePath e) ∩ range (D.edgePath f) = {D.vertex (edgeSource e),
      D.vertex (edgeTarget e)} ∩ {D.vertex (edgeSource f), D.vertex (edgeTarget f)} := by
  refine subset_antisymm ?_ (inter_subset_inter ?_ ?_)
  rotate_left
  · rintro _ (rfl | rfl) <;> simp
  · rintro _ (rfl | rfl) <;> simp
  have key {g h : E(G)} (hgh : g ≠ h) {z : X} {tg sh : I} (htg : D.edgePath g tg = z)
      (hsh : D.edgePath h sh = z) : z = D.vertex (edgeSource g) ∨ z = D.vertex (edgeTarget g) := by
    obtain rfl | rfl | htgI := (D.edgePath g).mem_range_iff_mem_interior_or_source_or_target z
      |>.mp (by simp [← htg])
    · tauto
    · tauto
    have hnotV : z ∉ range D.vertex :=
      (D.pathInterior_edgePath_disjoint_vertex g).notMem_of_mem_left htgI
    obtain rfl | rfl | hshI := unitInterval.eq_zero_or_eq_one_or_mem_Ioo sh
    · exact (hnotV ⟨edgeSource h, by rw [← hsh, Path.source]⟩).elim
    · exact (hnotV ⟨edgeTarget h, by rw [← hsh, Path.target]⟩).elim
    exact ((D.pathInterior_edgePath_disjoint hgh).notMem_of_mem_left htgI ⟨sh, hshI, hsh⟩).elim
  intro z ⟨⟨te, hte⟩, ⟨sf, hsf⟩⟩
  exact ⟨by simpa [mem_insert_iff, mem_singleton_iff] using key hef hte hsf,
    by simpa [mem_insert_iff, mem_singleton_iff] using key hef.symm hsf hte⟩

/-- The support of a drawing of a finite graph is compact. -/
lemma support_isCompact [G.Finite] (D : Drawing G X) : IsCompact D.support :=
  isCompact_range D.continuous

/-- In a Hausdorff space, the support of a drawing of a finite graph is closed. -/
lemma support_isClosed [G.Finite] [T2Space X] (D : Drawing G X) : IsClosed D.support :=
  D.support_isCompact.isClosed

/-- Postcompose a drawing with a continuous injection of ambient spaces. -/
def postcomp (D : Drawing G X) (f : C(X, Y)) (hf : Injective f) : Drawing G Y where
  toContinuousMap := f.comp D.toContinuousMap
  inj' := hf.comp D.injective

@[simp]
lemma postcomp_apply (D : Drawing G X) (f : C(X, Y)) (hf : Injective f)
    (x : Realization G) : D.postcomp f hf x = f (D x) :=
  rfl

/-! ### Constructors -/

/-- Construct a drawing from a map on the pre-realization that identifies exactly the points
identified by the realization quotient. -/
noncomputable def ofPreRealization (f : C(G.PreRealization, X))
    (map_eq_of_glueRel : ∀ a b, G.glueRel a b → f a = f b)
    (glueRel_of_map_eq : ∀ a b, f a = f b → G.glueRel a b) : Drawing G X where
  toContinuousMap :=
    ⟨Quotient.lift f map_eq_of_glueRel, continuous_quot_lift map_eq_of_glueRel f.continuous⟩
  inj' x y h := by
    induction x using Realization.ind with | h a =>
    induction y using Realization.ind with | h b =>
    exact Realization.mk_eq_mk.mpr (glueRel_of_map_eq a b h)

/-- Construct a drawing by assigning distinct points to vertices and internally disjoint paths to
edges.

The hypotheses allow loops and parallel edges. For a loop, the two endpoints of its path agree,
as prescribed by `edgeSource` and `edgeTarget`; only the open interval is required to be
injective. -/
noncomputable def preRealizationMapOfPaths (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) :
    C(G.PreRealization, X) :=
  ⟨Sum.elim vertex fun p ↦ edge p.1 p.2, continuous_sum_dom.mpr ⟨continuous_of_discreteTopology,
    continuous_sigma fun e ↦ (edge e).continuous⟩⟩

@[simp]
lemma preRealizationMapOfPaths_inl (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (x : V(G)) :
    preRealizationMapOfPaths vertex edge (Sum.inl x) = vertex x := rfl

@[simp]
lemma preRealizationMapOfPaths_inr (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (e : E(G))
    (t : unitInterval) :
    preRealizationMapOfPaths vertex edge (Sum.inr ⟨e, t⟩) = edge e t := rfl

/-- The endpoints of the paths are where the realization glues, so the map respects the relation.
This direction needs no hypothesis: it is `Path.source` and `Path.target`. -/
theorem map_eq_of_glueRel_preRealizationMapOfPaths (vertex : V(G) → X) {a b}
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (h : G.glueRel a b) :
    preRealizationMapOfPaths vertex edge a = preRealizationMapOfPaths vertex edge b := by
  induction h with
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ h₁ h₂ => exact h₁.trans h₂
  | rel x y hxy =>
    match x, y with
    | .inr _, _ => simp [glueRelAux] at hxy
    | .inl u, .inl v => rw [(glueRelAux_inl_inl_iff ..).mp hxy]
    | .inl u, .inr ⟨e, t⟩ =>
      obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := (glueRelAux_inl_inr_iff ..).mp hxy
      · simp [Path.source]
      · simp [Path.target]

/-- Conversely, the map identifies *only* what the realization glues. This is where all four
hypotheses are used, and it is the whole mathematical content of `ofVertexAndEdgePaths`. -/
theorem glueRel_of_map_eq_preRealizationMapOfPaths {a b} (vertex : V(G) → X)
    (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (edge e).Interior (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f → Disjoint (edge e).Interior (edge f).Interior)
    (h : preRealizationMapOfPaths vertex edge a = preRealizationMapOfPaths vertex edge b) :
    G.glueRel a b := by
  match a, b with
  | .inl u, .inl v => exact (glueRel_inl_inl_iff u v).mpr (vertex_injective (by simpa using h))
  | .inl u, .inr ⟨e, t⟩ =>
    have hvt : vertex u = edge e t := by simpa using h
    obtain rfl | ht0 := eq_or_ne t 0
    · exact (glueRel_inl_inr_iff u e 0).mpr <|
        .inl ⟨rfl, vertex_injective (by rwa [Path.source] at hvt)⟩
    rcases eq_or_ne t 1 with rfl | ht1
    · exact (glueRel_inl_inr_iff u e 1).mpr <|
        .inr ⟨rfl, vertex_injective (by simpa [Path.target] using hvt)⟩
    · exact ((edge_interior_disjoint_vertex e).notMem_of_mem_left
        ⟨t, ⟨unitInterval.pos_iff_ne_zero.mpr ht0, unitInterval.lt_one_iff_ne_one.mpr ht1⟩, rfl⟩
        ⟨u, hvt⟩).elim
  | .inr ⟨e, t⟩, .inl v =>
    have hvt : edge e t = vertex v := by simpa using h
    rcases eq_or_ne t 0 with rfl | ht0
    · exact (glueRel_inr_inl_iff e 0 v).mpr <|
        .inl ⟨rfl, vertex_injective (by simpa [Path.source] using hvt.symm)⟩
    rcases eq_or_ne t 1 with rfl | ht1
    · exact (glueRel_inr_inl_iff e 1 v).mpr <|
        .inr ⟨rfl, vertex_injective (by simpa [Path.target] using hvt.symm)⟩
    · exact ((edge_interior_disjoint_vertex e).notMem_of_mem_left
        ⟨t, ⟨unitInterval.pos_iff_ne_zero.mpr ht0, unitInterval.lt_one_iff_ne_one.mpr ht1⟩, rfl⟩
        ⟨v, hvt.symm⟩).elim
  | .inr ⟨e₁, t₁⟩, .inr ⟨e₂, t₂⟩ =>
    have heq : edge e₁ t₁ = edge e₂ t₂ := by simpa using h
    rcases eq_or_ne t₁ 0 with rfl | ht₁₀
    · rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · have hv : edgeSource e₁ = edgeSource e₂ :=
          vertex_injective (by simpa [Path.source] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 0 0).mpr <| Or.inr ⟨edgeSource e₁, by simp, ?_⟩
        simp [hv]
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · have hv : edgeSource e₁ = edgeTarget e₂ :=
          vertex_injective (by simpa [Path.source, Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 0 1).mpr <| Or.inr ⟨edgeSource e₁, by simp, ?_⟩
        simp [hv]
      · exact ((edge_interior_disjoint_vertex e₂).notMem_of_mem_left
          ⟨t₂, ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩, rfl⟩
          ⟨edgeSource e₁, by simpa [Path.source] using heq⟩).elim
    rcases eq_or_ne t₁ 1 with rfl | ht₁₁
    · rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · have hv : edgeTarget e₁ = edgeSource e₂ :=
          vertex_injective (by simpa [Path.source, Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 1 0).mpr <| Or.inr ⟨edgeTarget e₁, by simp, ?_⟩
        simp [hv]
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · have hv : edgeTarget e₁ = edgeTarget e₂ :=
          vertex_injective (by simpa [Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 1 1).mpr <| Or.inr ⟨edgeTarget e₁, by simp, ?_⟩
        simp [hv]
      · exact ((edge_interior_disjoint_vertex e₂).notMem_of_mem_left
          ⟨t₂, ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩, rfl⟩
          ⟨edgeTarget e₁, by simpa [Path.target] using heq⟩).elim
    · have ht₁ : t₁ ∈ Ioo (0 : I) 1 :=
        ⟨unitInterval.pos_iff_ne_zero.mpr ht₁₀, unitInterval.lt_one_iff_ne_one.mpr ht₁₁⟩
      rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · exact ((edge_interior_disjoint_vertex e₁).notMem_of_mem_left ⟨t₁, ht₁, rfl⟩
          ⟨edgeSource e₂, by simpa [Path.source] using heq.symm⟩).elim
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · exact ((edge_interior_disjoint_vertex e₁).notMem_of_mem_left ⟨t₁, ht₁, rfl⟩
          ⟨edgeTarget e₂, by simpa [Path.target] using heq.symm⟩).elim
      · have ht₂ : t₂ ∈ Ioo (0 : I) 1 :=
          ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩
        obtain rfl | he := eq_or_ne e₁ e₂
        · exact (glueRel_inr_inr_iff e₁ e₁ t₁ t₂).mpr <|
            Or.inl ⟨rfl, edge_injective e₁ ht₁ ht₂ heq⟩
        · exact ((edge_interior_disjoint e₁ e₂ he).notMem_of_mem_left
            ⟨t₁, ht₁, rfl⟩ ⟨t₂, ht₂, heq.symm⟩).elim

noncomputable def ofVertexAndEdgePaths
    (vertex : V(G) → X) (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (edge e).Interior (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f → Disjoint (edge e).Interior (edge f).Interior) :
    Drawing G X :=
  ofPreRealization (preRealizationMapOfPaths vertex edge)
    (fun _ _ ↦ map_eq_of_glueRel_preRealizationMapOfPaths vertex edge)
    (fun _ _ ↦ glueRel_of_map_eq_preRealizationMapOfPaths vertex vertex_injective edge
      edge_injective edge_interior_disjoint_vertex edge_interior_disjoint)

variable {vertex : V(G) → X} {edge : ∀ e : E(G), Path (vertex (edgeSource e))
  (vertex (edgeTarget e))} {hv : Injective vertex} {he : ∀ e, InjOn (edge e) (Ioo (0 : I) 1)}
  {hev : ∀ e, Disjoint (edge e).Interior (range vertex)}
  {hee : ∀ e f, e ≠ f → Disjoint (edge e).Interior (edge f).Interior}

@[simp]
lemma ofVertexAndEdgePaths_vertex (x : V(G)) :
    (ofVertexAndEdgePaths vertex hv edge he hev hee).vertex x = vertex x := rfl

@[simp]
lemma ofVertexAndEdgePaths_edgePath_apply (e : E(G)) (t : unitInterval) :
    (ofVertexAndEdgePaths vertex hv edge he hev hee).edgePath e t = edge e t := rfl

lemma range_edgePath_ofVertexAndEdgePaths (e : E(G)) :
    range ((ofVertexAndEdgePaths vertex hv edge he hev hee).edgePath e) = range (edge e) := rfl

/-- The empty graph has a drawing in every topological space, including the empty space. -/
noncomputable def bot (X : Type u) [TopologicalSpace X] : Drawing (⊥ : Graph α β) X :=
  ofPreRealization ⟨fun a ↦ isEmptyElim a, continuous_of_discreteTopology⟩
    (fun a ↦ isEmptyElim a) (fun a ↦ isEmptyElim a)

/-! ### Restriction and transport -/

/-- Restrict a drawing to a subgraph. -/
def restrict (D : Drawing G X) (h : H ≤ G) : Drawing H X where
  toContinuousMap := D.toContinuousMap.comp h.realizationContinuousMap
  inj' := D.injective.comp h.RealizationEmbedding_isEmbedding.injective

@[simp]
lemma restrict_apply (D : Drawing G X) (h : H ≤ G) (x : Realization H) :
    D.restrict h x = D (h.RealizationEmbedding x) := rfl

/-! Restriction changes neither the position of a vertex nor the image of an edge. The two
`edgeSource`/`edgeTarget` statements are the ones that would fail if the orientation of an edge
were chosen per graph rather than determined by its ends; they hold because `ArbRel` fixes one
linear order per *type*, so `IsSubgraph.source` and `IsSubgraph.target` are available. -/

@[simp]
lemma restrict_vertex (D : Drawing G X) (h : H ≤ G) (x : V(H)) :
    (D.restrict h).vertex x = D.vertex ⟨x.1, vertexSet_mono h x.2⟩ := by
  simp [vertex, restrict_apply]

lemma restrict_vertex_edgeSource (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    (D.restrict h).vertex (edgeSource e) = D.vertex (edgeSource ⟨e.1, edgeSet_mono h e.2⟩) := by
  rw [restrict_vertex]
  congr 1
  ext
  simp [edgeSource, h.source]

lemma restrict_vertex_edgeTarget (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    (D.restrict h).vertex (edgeTarget e) = D.vertex (edgeTarget ⟨e.1, edgeSet_mono h e.2⟩) := by
  rw [restrict_vertex]
  congr 1
  ext
  simp [edgeTarget, h.target]

@[simp]
lemma range_edgePath_restrict (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    range ((D.restrict h).edgePath e) = range (D.edgePath ⟨e.1, edgeSet_mono h e.2⟩) := by
  ext x
  simp only [mem_range]
  refine ⟨fun ⟨t, ht⟩ ↦ ⟨t, ?_⟩, fun ⟨t, ht⟩ ↦ ⟨t, ?_⟩⟩ <;>
    rw [← ht, edgePath_apply, edgePath_apply, restrict_apply, h.RealizationEmbedding_edgePath]

/-! ### Gluing two drawings

`union` below glues a drawing of `G₁` and a drawing of `G₂` into a drawing of `G₁ ∪ G₂`. It is pure
gluing: no metric, no plane, no finiteness, no `Loopless`. Every geometric fact is pushed into the
two hypotheses `Agree` and `hsupp`.

**Intended consumer.** Status.md §13.1 Lemma 13.2, *insertion*: adding one parallel edge or one
loop to an existing drawing. Take `G₂ := Graph.singleEdge u v f` (or `Graph.singleEdge u u f` for a
loop), so that `V(G₂)` is the one or two attachment vertices and `hsupp` reads exactly "the new arc
meets the old support only at those vertices" — which is what the routing primitive of §6.1 and the
sector construction of §13.1 respectively deliver. `Agree` is then immediate.

**Not** for gluing two planar graphs along a cut vertex or a shared edge. Status.md:970 retires
that: "no gluing of two drawings, no re-rooting of a face to infinity". The theorems that used to
sit at the bottom of this file are gone; see Kuratowski `Decisions.md` D17.

The layer is subdivided because the four obligations of `ofVertexAndEdgePaths` each split into the
same three cases — both edges in `G₁`, both in `G₂`, one of each — and the cross case is always the
same argument. That argument is `mem_range_vertex_of_mem_support_inter`, stated once.

Three design points, all load-bearing.

*`Agree` is a typing obligation, not a proof obligation.* Without it `unionEdge` does not elaborate.
See its docstring.

*Never state a computation lemma for `unionEdge` as an equation between paths.* `unionEdge … ed` and
`D₁.edgePath ⟨ed.1, h⟩` have different types — the endpoints differ by `unionVertex_edgeSource_left`
— so an equation between them is ill-typed and forces `HEq`. Mathlib's `Path.cast`
(`Mathlib/Topology/Path.lean:376`) keeps `toFun` definitionally, so `range` and `Path.Interior` see
straight through the cast: every computation lemma below is stated at the level of those two sets,
and each closes by `dite_eq_left`/`dite_eq_right` and then `rfl`.

*`Disjoint E(G₁) E(G₂)` is deliberately not assumed.* A shared edge is resolved in favour of `G₁`,
and no obligation below needs disjointness: `hsupp` already forbids the configuration that would
break injectivity — a shared arc lies in both supports and is not a vertex image. The insertion use
above never has a shared edge, so this costs nothing there. -/

section Gluing

variable {G₁ G₂ : Graph α β} (D₁ : Drawing G₁ X) (D₂ : Drawing G₂ X)

/-- `D₁` and `D₂` place every shared vertex at the same point of `X`.

This is a **typing** obligation, not a proof obligation: without it `unionEdge` does not elaborate.
An edge of `G₂` whose source is a vertex shared with `G₁` must be assigned a path *starting at*
`unionVertex D₁ D₂ (edgeSource _)`, which computes to `D₁.vertex …`, whereas `D₂.edgePath` starts at
`D₂.vertex …`. No amount of proof effort closes that gap; the hypothesis has to exist. -/
def Agree : Prop :=
  ∀ (x : α) (h₁ : x ∈ V(G₁)) (h₂ : x ∈ V(G₂)), D₁.vertex ⟨x, h₁⟩ = D₂.vertex ⟨x, h₂⟩

open Classical in
/-- The vertex placement of the glued drawing: use `D₁` where it is defined, `D₂` otherwise. -/
noncomputable def unionVertex (w : V(G₁ ∪ G₂)) : X :=
  if hw : w.1 ∈ V(G₁) then D₁.vertex ⟨w.1, hw⟩
  else D₂.vertex ⟨w.1, Or.resolve_left (show w.1 ∈ V(G₁) ∨ w.1 ∈ V(G₂) from w.2) hw⟩

@[simp]
lemma unionVertex_of_mem_left {w : V(G₁ ∪ G₂)} (hw : w.1 ∈ V(G₁)) :
    unionVertex D₁ D₂ w = D₁.vertex ⟨w.1, hw⟩ :=
  dite_eq_left hw

/-- The right-hand computation rule. Unlike the left one it needs `Agree`, because a vertex of `G₂`
may also be a vertex of `G₁`, in which case `unionVertex` took the `D₁` branch. -/
lemma unionVertex_of_mem_right (ha : D₁.Agree D₂) {w : V(G₁ ∪ G₂)} (hw : w.1 ∈ V(G₂)) :
    unionVertex D₁ D₂ w = D₂.vertex ⟨w.1, hw⟩ := by
  by_cases hw₁ : w.1 ∈ V(G₁)
  · rw [unionVertex_of_mem_left D₁ D₂ hw₁]
    exact ha w.1 hw₁ hw
  · rw [unionVertex, dite_eq_right hw₁]

lemma range_unionVertex (ha : D₁.Agree D₂) :
    range (unionVertex D₁ D₂) = range D₁.vertex ∪ range D₂.vertex := by
  sorry

/-! The four `edgeSource`/`edgeTarget` transport lemmas. They are the exact analogues of
`restrict_vertex_edgeSource` and `restrict_vertex_edgeTarget` above, and hold for the same reason:
`ArbRel` fixes one linear order per *type*, so `IsSubgraph.source` (`GraphLike/ArbRel.lean:93`) and
`IsSubgraph.target` are available for `G₁ ≤ G₁ ∪ G₂` and `G₂ ≤ G₁ ∪ G₂`. They exist only to make
`unionEdge` typecheck. -/

lemma unionVertex_edgeSource_left {ed : E(G₁ ∪ G₂)} (hed : ed.1 ∈ E(G₁)) :
    unionVertex D₁ D₂ (edgeSource ed) = D₁.vertex (edgeSource ⟨ed.1, hed⟩) := by
  sorry

lemma unionVertex_edgeTarget_left {ed : E(G₁ ∪ G₂)} (hed : ed.1 ∈ E(G₁)) :
    unionVertex D₁ D₂ (edgeTarget ed) = D₁.vertex (edgeTarget ⟨ed.1, hed⟩) := by
  sorry

lemma unionVertex_edgeSource_right (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) {ed : E(G₁ ∪ G₂)}
    (hed : ed.1 ∈ E(G₂)) :
    unionVertex D₁ D₂ (edgeSource ed) = D₂.vertex (edgeSource ⟨ed.1, hed⟩) := by
  sorry

lemma unionVertex_edgeTarget_right (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) {ed : E(G₁ ∪ G₂)}
    (hed : ed.1 ∈ E(G₂)) :
    unionVertex D₁ D₂ (edgeTarget ed) = D₂.vertex (edgeTarget ⟨ed.1, hed⟩) := by
  sorry

open Classical in
/-- The edge placement of the glued drawing. A shared edge is drawn by `D₁`. -/
noncomputable def unionEdge (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) (ed : E(G₁ ∪ G₂)) :
    Path (unionVertex D₁ D₂ (edgeSource ed)) (unionVertex D₁ D₂ (edgeTarget ed)) :=
  if hed : ed.1 ∈ E(G₁) then
    (D₁.edgePath ⟨ed.1, hed⟩).cast (unionVertex_edgeSource_left D₁ D₂ hed)
      (unionVertex_edgeTarget_left D₁ D₂ hed)
  else
    have hed₂ : ed.1 ∈ E(G₂) := Or.resolve_left (show ed.1 ∈ E(G₁) ∨ ed.1 ∈ E(G₂) from ed.2) hed
    (D₂.edgePath ⟨ed.1, hed₂⟩).cast (unionVertex_edgeSource_right D₁ D₂ hc ha hed₂)
      (unionVertex_edgeTarget_right D₁ D₂ hc ha hed₂)

/-! The four computation lemmas for `unionEdge`, at the level of `range` and `Path.Interior`. Each
is `rw [unionEdge, dite_eq_left hed]` (resp. `dite_eq_right`) followed by `rfl`: `Path.cast` does not change
`toFun`, so both sets are literally the same term. Do not attempt the path-level equation. -/

lemma range_unionEdge_left (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) {ed : E(G₁ ∪ G₂)}
    (hed : ed.1 ∈ E(G₁)) :
    range (unionEdge D₁ D₂ hc ha ed) = range (D₁.edgePath ⟨ed.1, hed⟩) := by
  sorry

lemma range_unionEdge_right (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) {ed : E(G₁ ∪ G₂)}
    (hed₁ : ed.1 ∉ E(G₁)) (hed : ed.1 ∈ E(G₂)) :
    range (unionEdge D₁ D₂ hc ha ed) = range (D₂.edgePath ⟨ed.1, hed⟩) := by
  sorry

lemma unionEdge_interior_left (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) {ed : E(G₁ ∪ G₂)}
    (hed : ed.1 ∈ E(G₁)) :
    (unionEdge D₁ D₂ hc ha ed).Interior = (D₁.edgePath ⟨ed.1, hed⟩).Interior := by
  sorry

lemma unionEdge_interior_right (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) {ed : E(G₁ ∪ G₂)}
    (hed₁ : ed.1 ∉ E(G₁)) (hed : ed.1 ∈ E(G₂)) :
    (unionEdge D₁ D₂ hc ha ed).Interior = (D₂.edgePath ⟨ed.1, hed⟩).Interior := by
  sorry

/-- **The workhorse of the cross case.** A point common to both supports is not merely *some* point
of `D₁`'s vertex set: it is a vertex image on *both* sides. That upgrade is what rules out a shared
point lying in the interior of an edge, and it discharges the mixed case of all four obligations
below.

The `hsupp` hypothesis is stated with `⊆` rather than `=` on purpose: given `Agree`, the reverse
inclusion is automatic, so the equality form would only make every call site harder. -/
lemma mem_range_vertex_of_mem_support_inter (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)}) {x : X}
    (h₁ : x ∈ D₁.support) (h₂ : x ∈ D₂.support) :
    x ∈ range D₁.vertex ∧ x ∈ range D₂.vertex := by
  sorry

/-! ### The four obligations of `ofVertexAndEdgePaths`

Each splits on membership in `E(G₁)`/`V(G₁)` into a `D₁` case, a `D₂` case and a cross case. The
first two are the corresponding fact for `D₁` or `D₂` transported along the computation lemmas
above; the cross case is `mem_range_vertex_of_mem_support_inter` followed by
`pathInterior_edgePath_disjoint_vertex`. -/

lemma unionVertex_injective (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)}) :
    Injective (unionVertex D₁ D₂) := by
  sorry

lemma unionEdge_injOn (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂) (ed : E(G₁ ∪ G₂)) :
    InjOn (unionEdge D₁ D₂ hc ha ed) (Ioo (0 : unitInterval) 1) := by
  sorry

lemma unionEdge_interior_disjoint_range_unionVertex (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)})
    (ed : E(G₁ ∪ G₂)) :
    Disjoint (unionEdge D₁ D₂ hc ha ed).Interior (range (unionVertex D₁ D₂)) := by
  sorry

lemma unionEdge_interior_disjoint (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)})
    (ed₁ ed₂ : E(G₁ ∪ G₂)) (hne : ed₁ ≠ ed₂) :
    Disjoint (unionEdge D₁ D₂ hc ha ed₁).Interior (unionEdge D₁ D₂ hc ha ed₂).Interior := by
  sorry

/-- **Gluing.** Two drawings that agree on the shared vertices and meet nowhere else assemble into a
drawing of the union.

This is a genuine definition: its data — where each vertex goes and which arc each edge follows —
is completely determined by `unionVertex` and `unionEdge`, so `union_vertex` and the two
`range_edgePath` lemmas below hold by `rfl` no matter how the four obligations are eventually
proved. That is the reason for splitting them out rather than leaving the whole `def` open. -/
noncomputable def union (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)}) :
    Drawing (G₁ ∪ G₂) X :=
  ofVertexAndEdgePaths (unionVertex D₁ D₂) (unionVertex_injective D₁ D₂ ha hsupp)
    (unionEdge D₁ D₂ hc ha) (unionEdge_injOn D₁ D₂ hc ha)
    (unionEdge_interior_disjoint_range_unionVertex D₁ D₂ hc ha hsupp)
    fun _ _ ↦ unionEdge_interior_disjoint D₁ D₂ hc ha hsupp _ _

@[simp]
lemma union_vertex (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)})
    (w : V(G₁ ∪ G₂)) : (union D₁ D₂ hc ha hsupp).vertex w = unionVertex D₁ D₂ w :=
  rfl

lemma range_edgePath_union (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)})
    (ed : E(G₁ ∪ G₂)) :
    range ((union D₁ D₂ hc ha hsupp).edgePath ed) = range (unionEdge D₁ D₂ hc ha ed) :=
  rfl

/-- The support of a glued drawing is the union of the two supports. This is what lets a caller
iterate `union`, and what turns a hypothesis about `D₁.support ∪ D₂.support` into one about the
glued drawing. -/
lemma union_support (hc : G₁.Compatible G₂) (ha : D₁.Agree D₂)
    (hsupp : D₁.support ∩ D₂.support ⊆ D₁.vertex '' {w : V(G₁) | w.1 ∈ V(G₂)}) :
    (union D₁ D₂ hc ha hsupp).support = D₁.support ∪ D₂.support := by
  sorry

end Gluing

end Drawing

namespace Iso

open TopologicalModel unitInterval

/-- The image of a vertex under a graph isomorphism, as a subtype. -/
noncomputable abbrev vert (F : Iso K G) (x : V(K)) : V(G) :=
  isoVert F x

/-- The image of an edge under a graph isomorphism, as a subtype. -/
noncomputable abbrev edge (F : Iso K G) (e : E(K)) : E(G) :=
  isoEdge F e

lemma isLink_vert_edge (F : Iso K G) (e : E(K)) :
    G.IsLink (F.edge e) (F.vert (edgeSource e)) (F.vert (edgeTarget e)) :=
  F.map_isLink (isLink_edgeSource_edgeTarget e) (isoEdge_spec F e)
    (isoVert_spec F _) (isoVert_spec F _)

/-- Whether `F` sends the preferred orientation of `e` to that of its image. -/
abbrev sameOrientation (F : Iso K G) (e : E(K)) : Prop :=
  F.vert (edgeSource e) = edgeSource (F.edge e)

lemma sameOrientation_or_swap (F : Iso K G) (e : E(K)) :
    F.sameOrientation e ∨
      (F.vert (edgeSource e) = edgeTarget (F.edge e) ∧
        F.vert (edgeTarget e) = edgeSource (F.edge e)) := by
  obtain ⟨h₁, h₂⟩ | ⟨h₁, h₂⟩ :=
    (isLink_edgeSource_edgeTarget (F.edge e)).eq_and_eq_or_eq_and_eq (F.isLink_vert_edge e)
  · exact Or.inl <| Subtype.ext h₁.symm
  · exact Or.inr ⟨Subtype.ext h₂.symm, Subtype.ext h₁.symm⟩

lemma vert_edgeTarget_of_sameOrientation (F : Iso K G) {e : E(K)} (h : F.sameOrientation e) :
    F.vert (edgeTarget e) = edgeTarget (F.edge e) := by
  obtain ⟨_, h₂⟩ | ⟨h₁, h₂⟩ :=
    (isLink_edgeSource_edgeTarget (F.edge e)).eq_and_eq_or_eq_and_eq (F.isLink_vert_edge e)
  · exact Subtype.ext h₂.symm
  · have hsrc : F.vert (edgeSource e) = F.vert (edgeTarget e) := by
      rw [h, Subtype.ext_iff.mpr h₁]
    exact hsrc.symm.trans (Subtype.ext h₂.symm)

lemma vert_of_not_sameOrientation (F : Iso K G) {e : E(K)} (h : ¬ F.sameOrientation e) :
    F.vert (edgeSource e) = edgeTarget (F.edge e) ∧
      F.vert (edgeTarget e) = edgeSource (F.edge e) :=
  (F.sameOrientation_or_swap e).resolve_left h

/-- Reparametrization of the unit interval along `e`, flipping if `F` reverses orientation. -/
noncomputable def orient (F : Iso K G) (e : E(K)) : I → I :=
  open Classical in fun t ↦ if F.sameOrientation e then t else σ t

lemma continuous_orient (F : Iso K G) (e : E(K)) : Continuous (F.orient e) := by
  classical
  by_cases h : F.sameOrientation e
  · convert continuous_id (X := I)
    ext t
    simp [orient, ite_eq_left h]
  · convert continuous_symm
    ext t
    simp [orient, ite_eq_right h]

/-- The induced map on pre-realizations. -/
noncomputable def preRealizationMap (F : Iso K G) : C(K.PreRealization, G.PreRealization) where
  toFun
    | .inl v => .inl (F.vert v)
    | .inr ⟨e, t⟩ => .inr ⟨F.edge e, F.orient e t⟩
  continuous_toFun := continuous_sum_dom.mpr ⟨continuous_of_discreteTopology,
    continuous_sigma_iff.mpr fun e ↦ continuous_inr.comp <|
      continuous_sigmaMk.comp (F.continuous_orient e)⟩

lemma preRealizationMap_glueRel (F : Iso K G) ⦃a b : K.PreRealization⦄
    (h : K.glueRel a b) : G.glueRel (F.preRealizationMap a) (F.preRealizationMap b) := by
  classical
  induction h with
  | refl => rfl
  | symm _ _ _ ih => exact Setoid.symm ih
  | trans _ _ _ _ _ h₁ h₂ => exact Setoid.trans h₁ h₂
  | rel x y hxy =>
    match x, y with
    | .inr _, _ => simp [glueRelAux] at hxy
    | .inl u, .inl v => rw [(glueRelAux_inl_inl_iff ..).mp hxy]
    | .inl u, .inr ⟨e, t⟩ =>
      obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := (glueRelAux_inl_inr_iff ..).mp hxy <;>
        by_cases hori : F.sameOrientation e
      · convert (glueRel_inl_inr_iff (edgeSource (F.edge e)) (F.edge e) 0).mpr
          (.inl ⟨rfl, rfl⟩) using 1
        · simpa [preRealizationMap] using hori
        · simp [preRealizationMap, orient, ite_eq_left hori]
      · obtain ⟨hs, _⟩ := F.vert_of_not_sameOrientation hori
        convert (glueRel_inl_inr_iff (edgeTarget (F.edge e)) (F.edge e) 1).mpr
          (.inr ⟨rfl, rfl⟩) using 1
        · simpa [preRealizationMap] using hs
        · simp [preRealizationMap, orient, ite_eq_right hori]
      · convert (glueRel_inl_inr_iff (edgeTarget (F.edge e)) (F.edge e) 1).mpr
          (.inr ⟨rfl, rfl⟩) using 1
        · simpa [preRealizationMap] using F.vert_edgeTarget_of_sameOrientation hori
        · simp [preRealizationMap, orient, ite_eq_left hori]
      · obtain ⟨_, ht⟩ := F.vert_of_not_sameOrientation hori
        convert (glueRel_inl_inr_iff (edgeSource (F.edge e)) (F.edge e) 0).mpr
          (.inl ⟨rfl, rfl⟩) using 1
        · simpa [preRealizationMap] using ht
        · simp [preRealizationMap, orient, ite_eq_right hori]

lemma vert_symm_vert (F : Iso K G) (x : V(K)) : F.symm.vert (F.vert x) = x := by
  ext
  change (F.vertMap.symm (F.vert x).val).get _ = x.val
  have hx : F.vertMap.symm (F.vert x).val = some x.val :=
    (F.vertMap.eq_some_iff).mpr (isoVert_spec F x)
  simp [hx]

lemma vert_vert_symm (F : Iso K G) (y : V(G)) : F.vert (F.symm.vert y) = y := by
  ext
  change (F.vertMap (F.symm.vert y).val).get _ = y.val
  have hy : F.vertMap (F.symm.vert y).val = some y.val :=
    (F.vertMap.eq_some_iff).mp (isoVert_spec F.symm y)
  simp [hy]

lemma edge_symm_edge (F : Iso K G) (e : E(K)) : F.symm.edge (F.edge e) = e := by
  ext
  change (F.edgeMap.symm (F.edge e).val).get _ = e.val
  have he : F.edgeMap.symm (F.edge e).val = some e.val :=
    (F.edgeMap.eq_some_iff).mpr (isoEdge_spec F e)
  simp [he]

lemma edge_edge_symm (F : Iso K G) (e : E(G)) : F.edge (F.symm.edge e) = e := by
  ext
  change (F.edgeMap (F.symm.edge e).val).get _ = e.val
  have he : F.edgeMap (F.symm.edge e).val = some e.val :=
    (F.edgeMap.eq_some_iff).mp (isoEdge_spec F.symm e)
  simp [he]

lemma sameOrientation_symm (F : Iso K G) {e : E(K)} (h : F.sameOrientation e) :
    F.symm.sameOrientation (F.edge e) := by
  unfold sameOrientation at h ⊢
  simpa [vert_symm_vert, edge_symm_edge] using congrArg F.symm.vert h.symm

lemma not_sameOrientation_symm (F : Iso K G) {e : E(K)} (h : ¬ F.sameOrientation e) :
    ¬ F.symm.sameOrientation (F.edge e) := by
  intro hs
  unfold sameOrientation at hs
  have hs' : F.symm.vert (edgeSource (F.edge e)) = edgeSource e := by
    simpa [edge_symm_edge] using hs
  have : F.vert (edgeSource e) = edgeSource (F.edge e) := by
    simpa [vert_vert_symm] using congrArg F.vert hs'.symm
  exact h this

lemma sameOrientation_edge_symm (F : Iso K G) (e : E(G)) :
    F.sameOrientation (F.symm.edge e) ↔ F.symm.sameOrientation e := by
  refine ⟨fun h ↦ ?_, fun h ↦ ?_⟩ <;> unfold sameOrientation at h ⊢
  · have h' : F.vert (edgeSource (F.symm.edge e)) = edgeSource e := by
      simpa [edge_edge_symm] using h
    simpa [vert_symm_vert] using congrArg F.symm.vert h'.symm
  · have := congrArg F.vert h
    simpa [vert_vert_symm, edge_edge_symm] using this.symm

lemma orient_symm_orient (F : Iso K G) (e : E(K)) (t : I) :
    F.symm.orient (F.edge e) (F.orient e t) = t := by
  by_cases h : F.sameOrientation e
  · simp [orient, ite_eq_left h, ite_eq_left (F.sameOrientation_symm h)]
  · simp [orient, ite_eq_right h, ite_eq_right (F.not_sameOrientation_symm h), symm_symm]

lemma orient_orient_symm (F : Iso K G) (e : E(G)) (t : I) :
    F.orient (F.symm.edge e) (F.symm.orient e t) = t := by
  by_cases h : F.symm.sameOrientation e
  · simp [orient, ite_eq_left h, ite_eq_left ((F.sameOrientation_edge_symm e).mpr h)]
  · simp [orient, ite_eq_right h, ite_eq_right (mt (F.sameOrientation_edge_symm e).mp h), symm_symm]

lemma preRealizationMap_symm_comp (F : Iso K G) (x : K.PreRealization) :
    F.symm.preRealizationMap (F.preRealizationMap x) = x := by
  match x with
  | .inl v => simp only [preRealizationMap, ContinuousMap.coe_mk, vert_symm_vert]
  | .inr ⟨e, t⟩ =>
    simp only [preRealizationMap, ContinuousMap.coe_mk, edge_symm_edge, orient_symm_orient]

lemma preRealizationMap_comp_symm (F : Iso K G) (x : G.PreRealization) :
    F.preRealizationMap (F.symm.preRealizationMap x) = x := by
  match x with
  | .inl v => simp only [preRealizationMap, ContinuousMap.coe_mk, vert_vert_symm]
  | .inr ⟨e, t⟩ =>
    simp only [preRealizationMap, ContinuousMap.coe_mk, edge_edge_symm, orient_orient_symm]

/-- The homeomorphism of weak realizations induced by a graph isomorphism. -/
noncomputable def realizationHomeomorph (F : Iso K G) : Realization K ≃ₜ Realization G where
  toFun := Quotient.map F.preRealizationMap F.preRealizationMap_glueRel
  invFun := Quotient.map F.symm.preRealizationMap F.symm.preRealizationMap_glueRel
  left_inv x := by
    induction x using Realization.ind with | h a =>
    exact congrArg (Realization.mk K) (F.preRealizationMap_symm_comp a)
  right_inv x := by
    induction x using Realization.ind with | h a =>
    exact congrArg (Realization.mk G) (F.preRealizationMap_comp_symm a)
  continuous_toFun :=
    continuous_coinduced_dom.mpr <| continuous_coinduced_rng.comp F.preRealizationMap.continuous
  continuous_invFun := continuous_coinduced_dom.mpr <|
    continuous_coinduced_rng.comp F.symm.preRealizationMap.continuous

end Iso

namespace Drawing

/-- Pull a drawing back along a graph isomorphism. -/
noncomputable def ofIso (D : Drawing G X) (F : Iso K G) : Drawing K X where
  toContinuousMap :=
    ⟨D ∘ F.realizationHomeomorph, D.continuous.comp F.realizationHomeomorph.continuous⟩
  inj' := D.injective.comp F.realizationHomeomorph.injective

/-- A drawing `D'` extends `D` along the subgraph inclusion `h`. -/
def Extends (D' : Drawing G X) (D : Drawing H X) (h : H ≤ G) : Prop :=
  ∀ x, D' (h.RealizationEmbedding x) = D x

/-! ### Drawability and planarity -/

end Drawing

/-- A graph is drawable in `X` if its weak realization admits a continuous injection into `X`. -/
def IsDrawable (G : Graph α β) (X : Type u) [TopologicalSpace X] : Prop :=
  Nonempty (Drawing G X)

/-- A graph is planar if it has a drawing in the Euclidean plane. -/
def Planar (G : Graph α β) : Prop :=
  G.IsDrawable (EuclideanSpace ℝ (Fin 2))

/-- The empty graph is drawable in every topological space. -/
theorem bot_isDrawable (X : Type u) [TopologicalSpace X] :
    (⊥ : Graph α β).IsDrawable X :=
  ⟨Drawing.bot X⟩

/-- The empty graph is planar. -/
theorem bot_planar : (⊥ : Graph α β).Planar :=
  bot_isDrawable (EuclideanSpace ℝ (Fin 2))

namespace IsDrawable

/-- Drawability is inherited by subgraphs. -/
lemma anti (hG : G.IsDrawable X) (hHG : H ≤ G) : H.IsDrawable X :=
  ⟨hG.some.restrict hHG⟩

/-- Drawability is invariant under graph isomorphism. -/
lemma of_iso (hG : G.IsDrawable X) (F : Iso K G) : K.IsDrawable X :=
  ⟨hG.some.ofIso F⟩

/-- Drawability is inherited by topological minors. -/
/- **Handoff to formalisation helper.** Needs a `Drawing` of `H` from a `Drawing` of `G` along a
`TopologicalModel` / `IsTopologicalMinor`: concatenate `D.edgePath` along each route, and check
disjointness of open cells against `route_internal_disjoint` / `route_edge_disjoint`. No named
`Drawing.ofTopologicalModel` (or equivalent) exists; building it is scaffolding, not a one-line
fill from `restrict`/`ofIso`. -/
theorem isTopologicalMinor (hG : G.IsDrawable X) (hHG : H.IsTopologicalMinor G) : H.IsDrawable X := by
  sorry

end IsDrawable

namespace Planar

/-- Planarity is inherited by subgraphs. -/
lemma anti (hG : G.Planar) (hHG : H ≤ G) : H.Planar :=
  IsDrawable.anti hG hHG

/-- Planarity is invariant under graph isomorphism. -/
lemma of_iso (hG : G.Planar) (F : Iso K G) : K.Planar :=
  IsDrawable.of_iso hG F

/-- Planarity is inherited by topological minors. -/
theorem isTopologicalMinor (hG : G.Planar) (hHG : H.IsTopologicalMinor G) : H.Planar :=
  IsDrawable.isTopologicalMinor hG hHG

/- **Removed 2026-08-13.** Two union theorems used to sit here —
`union_of_vertexSet_inter_subsingleton` (planar ∪ planar along at most one vertex) and
`union_of_common_nonloop_edge` — together with `IsForest.planar`, their only consumer. All three are
deleted, not moved.

They are out of plan. Status.md:970 is explicit: "There is no decomposition object, **no gluing of
two drawings, no re-rooting of a face to infinity**, and no polygonal Schoenflies anywhere below.
Earlier revisions of this note called for those; they are not needed." Status.md:1287 repeats the
warning for §13.5–§13.6, and no row of the §12 dependency table consumes a union of drawings. The
three had no consumer in the tree either, transitively.

Supplying the gluing hypotheses would have required exactly the second item on that retired list —
re-rooting a face to infinity, to put a marked vertex on the outer face — so the cost was real and
the plan had already declined to pay it. See Kuratowski `Decisions.md` D17 for the full record,
including the parts of the analysis worth keeping.

`Drawing.union` above stays: it is combinatorial, it needs nothing downstream, and §13.1's Lemma
13.2 has a use for it. Recover the deleted statements from git if §13 ever changes its mind. -/

end Planar

abbrev Plane := EuclideanSpace ℝ (Fin 2)

/-- Embed a finite type into the plane along the x-axis. -/
noncomputable def embedFinite (ι : Type*) [Finite ι] : ι → Plane :=
  fun i => EuclideanSpace.single 0 (Finite.equivFin ι i : ℝ)

lemma embedFinite_injective (ι : Type*) [Finite ι] : Injective (embedFinite ι) := by
  intro a b h
  have : (Finite.equivFin ι a : ℝ) = (Finite.equivFin ι b : ℝ) := by
    simpa [embedFinite, PiLp.single_apply] using congrArg (fun v : Plane => v 0) h
  exact (Finite.equivFin ι).injective (Fin.val_injective (Nat.cast_injective this))

lemma Path.interior_segment (a b : Plane) :
    (Path.segment a b).Interior = openSegment ℝ a b := by
  ext z
  constructor
  · rintro ⟨t, ht, rfl⟩
    rw [openSegment_eq_image_lineMap]
    exact ⟨t, ht, by simp [Path.segment_apply]⟩
  · rw [openSegment_eq_image_lineMap]
    rintro ⟨t, ht, rfl⟩
    exact ⟨⟨t, ht.1.le, ht.2.le⟩, ht, by simp [Path.segment_apply]⟩

/-- An edgeless finite graph is planar. -/
theorem noEdge_planar (V : Set α) (hV : V.Finite) : (Graph.noEdge V β).Planar := by
  have : (Graph.noEdge V β).Finite := (noEdge_finite V).mpr hV
  have : Finite ↑V(Graph.noEdge V β) := by
    simpa [vertexSet_noEdge] using hV.to_subtype
  refine ⟨Drawing.ofVertexAndEdgePaths (embedFinite _) (embedFinite_injective _)
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed _ _ => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))⟩

lemma singleEdge_edgeSource_ne_edgeTarget {x y : α} (hxy : x ≠ y) (e : β)
    (f : E(Graph.singleEdge x y e)) : edgeSource f ≠ edgeTarget f := by
  intro heq
  have hlink := isLink_edgeSource_edgeTarget f
  have hf : (f : β) = e := by simpa [edgeSet_singleEdge] using f.2
  have heq' : (edgeSource f : α) = edgeTarget f := congrArg Subtype.val heq
  rw [singleEdge_isLink_iff, hf, heq'] at hlink
  obtain ⟨-, hs⟩ := hlink
  obtain ⟨h1, h2⟩ | ⟨h1, h2⟩ := Sym2.eq_iff.mp hs
  · exact hxy (h1.symm.trans h2)
  · exact hxy (h2.symm.trans h1)

/-- A nonloop edge is planar. -/
theorem singleEdge_planar {x y : α} (hxy : x ≠ y) (e : β) : (Graph.singleEdge x y e).Planar := by
  set G := Graph.singleEdge x y e
  have : Finite ↑V(G) := by
    change Finite ↑({x, y} : Set α)
    infer_instance
  let e' : E(G) := ⟨e, by simp [G]⟩
  set vertex : V(G) → Plane := embedFinite V(G)
  have hv : Injective vertex := embedFinite_injective _
  have he : ∀ f : E(G), f = ⟨e, by simp [G]⟩ := by simp [G]
  have hne : ∀ f : E(G), edgeSource f ≠ edgeTarget f :=
    fun f ↦ singleEdge_edgeSource_ne_edgeTarget hxy e f
  set edge : ∀ f : E(G), Path (vertex (edgeSource f)) (vertex (edgeTarget f)) :=
    fun f => Path.segment (vertex (edgeSource f)) (vertex (edgeTarget f))
  refine ⟨Drawing.ofVertexAndEdgePaths vertex hv edge (fun f _ _ _ _ heq ↦
    Path.segment_injective_of_ne (hv.ne (hne f)) heq) (fun f ↦ disjoint_left.mpr ?_)
    fun f g hfg ↦ by grind⟩
  obtain rfl := he f
  rintro z ⟨t, ht, rfl⟩ ⟨v, hvz⟩
  have hzopen : edge e' t ∈ openSegment ℝ (vertex (edgeSource e')) (vertex (edgeTarget e')) := by
    simpa [← Path.interior_segment] using ⟨t, ht, rfl⟩
  have hlink : s((edgeSource e' : α), (edgeTarget e' : α)) = s(x, y) := by
    rw [← isLink_edgeSource_edgeTarget e' |>.isLink_iff_sym2_eq]
    simp only [singleEdge_isLink, and_self, true_or, G, e']
  have hvxy : (v : α) = x ∨ (v : α) = y := by
    simpa [G, vertexSet_singleEdge] using v.2
  obtain hmap | hmap : vertex v = vertex (edgeSource e') ∨ vertex v = vertex (edgeTarget e') := by
    obtain ⟨hs, ht⟩ | ⟨hs, ht⟩ := Sym2.eq_iff.mp hlink <;> obtain hvx | hvy := hvxy
    · exact Or.inl (congrArg vertex (Subtype.ext (hvx.trans hs.symm)))
    · exact Or.inr (congrArg vertex (Subtype.ext (hvy.trans ht.symm)))
    · exact Or.inr (congrArg vertex (Subtype.ext (hvx.trans ht.symm)))
    · exact Or.inl (congrArg vertex (Subtype.ext (hvy.trans hs.symm)))
  · exact hv.ne (hne e') (left_mem_openSegment_iff.mp (by rwa [← hvz, hmap] at hzopen))
  · exact hv.ne (hne e') (right_mem_openSegment_iff.mp (by rwa [← hvz, hmap] at hzopen))

/-! ### Straight-line drawing on at most four vertices -/

private def toPlane (x y : ℝ) : Plane := (WithLp.equiv 2 (Fin 2 → ℝ)).symm ![x, y]

@[simp] private lemma toPlane_zero (x y : ℝ) : toPlane x y 0 = x := by simp [toPlane]
@[simp] private lemma toPlane_one (x y : ℝ) : toPlane x y 1 = y := by simp [toPlane]

/-- Four plane points realizing a triangle with an interior vertex: `(0,0)`, `(2,0)`, `(0,2)`,
`(1,1/2)`. -/
private def pts4 : Fin 4 → Plane :=
  ![toPlane 0 0, toPlane 2 0, toPlane 0 2, toPlane 1 (1 / 2)]

private lemma pts4_injective : Injective pts4 := by
  intro a b h
  have hx := congrArg (fun v : Plane => v 0) h
  have hy := congrArg (fun v : Plane => v 1) h
  fin_cases a <;> fin_cases b <;> simp [pts4] at hx hy ⊢

private lemma linInd_of_det {u v : Plane} (h : u 0 * v 1 - u 1 * v 0 ≠ 0) :
    LinearIndependent ℝ ![u, v] := by
  rw [linearIndependent_fin2]
  refine ⟨?_, fun a ha => ?_⟩
  · intro hv
    exact h (by
      have hv0 : v 0 = 0 := by simpa using congrArg (fun w : Plane => w 0) hv
      have hv1 : v 1 = 0 := by simpa using congrArg (fun w : Plane => w 1) hv
      simp [hv0, hv1])
  · have h0 := congrArg (fun w : Plane => w 0) ha
    have h1 := congrArg (fun w : Plane => w 1) ha
    simp [PiLp.smul_apply] at h0 h1
    refine h ?_
    calc
      u 0 * v 1 - u 1 * v 0
          = (a * v 0) * v 1 - (a * v 1) * v 0 := by rw [← h0, ← h1]
        _ = 0 := by ring

private lemma det_pts4_star {c x y : Fin 4} (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    (pts4 x - pts4 c) 0 * (pts4 y - pts4 c) 1 -
      (pts4 x - pts4 c) 1 * (pts4 y - pts4 c) 0 ≠ 0 := by
  fin_cases c <;> fin_cases x <;> fin_cases y <;>
    simp_all [pts4, PiLp.sub_apply] <;> norm_num

private lemma linearIndependent_pts4_star {c x y : Fin 4}
    (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    LinearIndependent ℝ ![pts4 x - pts4 c, pts4 y - pts4 c] :=
  linInd_of_det (det_pts4_star hx hy hxy)

private lemma openSegment_star_disjoint {c x y : Fin 4}
    (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    Disjoint (openSegment ℝ (pts4 c) (pts4 x)) (openSegment ℝ (pts4 c) (pts4 y)) := by
  refine disjoint_left.2 fun p hpx hpy => ?_
  have hinter : p ∈ segment ℝ (pts4 c) (pts4 x) ∩ segment ℝ (pts4 c) (pts4 y) :=
    ⟨openSegment_subset_segment _ _ _ hpx, openSegment_subset_segment _ _ _ hpy⟩
  have hp : p = pts4 c := by
    have := segment_inter_eq_endpoint_of_linearIndependent_sub ℝ
      (linearIndependent_pts4_star hx hy hxy)
    simpa [this] using hinter
  have : pts4 c = pts4 x := (left_mem_openSegment_iff (y := pts4 x)).mp (by rwa [hp] at hpx)
  exact hx (pts4_injective this.symm)

private lemma not_mem_openSegment_pts4 {i j k : Fin 4}
    (hij : i ≠ j) (hik : k ≠ i) (hjk : k ≠ j) :
    pts4 k ∉ openSegment ℝ (pts4 i) (pts4 j) := by
  intro h
  rw [openSegment_eq_image'] at h
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := h
  have hx := congrArg (fun v : Plane => v 0) heq
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx hy
  fin_cases i <;> fin_cases j <;> fin_cases k <;>
    simp_all [pts4] <;> (try linarith)

private lemma openSegment_eq_of_sym2 {a b c d : Fin 4} (h : s(a, b) = s(c, d)) :
    openSegment ℝ (pts4 a) (pts4 b) = openSegment ℝ (pts4 c) (pts4 d) := by
  rcases (Sym2.eq_iff).mp h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · rfl
  · exact openSegment_symm _ _ _

private lemma openSegment_01_23 :
    Disjoint (openSegment ℝ (pts4 0) (pts4 1)) (openSegment ℝ (pts4 2) (pts4 3)) := by
  refine disjoint_left.2 fun p hp01 hp23 => ?_
  rw [openSegment_eq_image'] at hp01 hp23
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp01
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp23
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hy
  have : t = 4 / 3 := by ring_nf at hy; linarith
  linarith

private lemma openSegment_02_13 :
    Disjoint (openSegment ℝ (pts4 0) (pts4 2)) (openSegment ℝ (pts4 1) (pts4 3)) := by
  refine disjoint_left.2 fun p hp01 hp23 => ?_
  rw [openSegment_eq_image'] at hp01 hp23
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp01
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp23
  have hx := congrArg (fun v : Plane => v 0) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx
  have : t = 2 := by linarith
  linarith

private lemma openSegment_12_03 :
    Disjoint (openSegment ℝ (pts4 1) (pts4 2)) (openSegment ℝ (pts4 0) (pts4 3)) := by
  refine disjoint_left.2 fun p hp12 hp03 => ?_
  rw [openSegment_eq_image'] at hp12 hp03
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp12
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp03
  have hx := congrArg (fun v : Plane => v 0) heq
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx hy
  have hs : s = 1 / 3 := by
    have ht : t = 2 - 2 * s := by linarith
    have : 2 * s = t / 2 := by linarith
    rw [ht] at this; linarith
  have : t = 4 / 3 := by linarith
  linarith

private lemma exists_canon_edge {a b : Fin 4} (hab : a ≠ b) :
    ∃ u v : Fin 4, u < v ∧ s(a, b) = s(u, v) := by
  wlog hlt : a < b generalizing a b
  · obtain ⟨u, v, huv, heq⟩ := this hab.symm (lt_of_le_of_ne (le_of_not_gt hlt) hab.symm)
    exact ⟨u, v, huv, by simpa [Sym2.eq_swap] using heq⟩
  exact ⟨a, b, hlt, rfl⟩

private lemma openSegment_pts4_disjoint_complementary {u v u' v' : Fin 4}
    (huv : u < v) (huv' : u' < v') (hne : s(u, v) ≠ s(u', v'))
    (hdisj : Disjoint ({u, v} : Set (Fin 4)) {u', v'}) :
    Disjoint (openSegment ℝ (pts4 u) (pts4 v)) (openSegment ℝ (pts4 u') (pts4 v')) := by
  fin_cases u <;> fin_cases v <;> fin_cases u' <;> fin_cases v' <;>
    simp_all [Fin.lt_def] <;>
    first
    | exact openSegment_01_23
    | exact openSegment_02_13
    | exact openSegment_12_03
    | exact openSegment_01_23.symm
    | exact openSegment_02_13.symm
    | exact openSegment_12_03.symm

private lemma openSegment_pts4_disjoint {i j k ℓ : Fin 4}
    (hij : i ≠ j) (hkl : k ≠ ℓ) (hne : s(i, j) ≠ s(k, ℓ)) :
    Disjoint (openSegment ℝ (pts4 i) (pts4 j)) (openSegment ℝ (pts4 k) (pts4 ℓ)) := by
  obtain ⟨u, v, huv, heq1⟩ := exists_canon_edge hij
  obtain ⟨u', v', huv', heq2⟩ := exists_canon_edge hkl
  have hne' : s(u, v) ≠ s(u', v') := fun h => hne (heq1.trans (h.trans heq2.symm))
  rw [openSegment_eq_of_sym2 heq1, openSegment_eq_of_sym2 heq2]
  by_cases hshare : ({u, v} ∩ {u', v'} : Set (Fin 4)).Nonempty
  · obtain ⟨c, hc⟩ := hshare
    have hc1 : c ∈ ({u, v} : Set _) := hc.1
    have hc2 : c ∈ ({u', v'} : Set _) := hc.2
    let x : Fin 4 := if c = u then v else u
    let y : Fin 4 := if c = u' then v' else u'
    have hx : x ≠ c := by
      dsimp [x]; split_ifs with hcu
      · exact hcu ▸ huv.ne'
      · have : c = v := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc1
          exact hc1.resolve_left hcu
        exact this ▸ huv.ne
    have hy : y ≠ c := by
      dsimp [y]; split_ifs with hcu
      · exact hcu ▸ huv'.ne'
      · have : c = v' := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc2
          exact hc2.resolve_left hcu
        exact this ▸ huv'.ne
    have hxy : x ≠ y := by
      intro heqxy
      apply hne'
      have e1 : s(u, v) = s(c, x) := by
        dsimp [x]; split_ifs with hcu
        · subst hcu; rfl
        · have : c = v := by
            simp only [mem_insert_iff, mem_singleton_iff] at hc1
            exact hc1.resolve_left hcu
          subst this; exact Sym2.eq_swap
      have e2 : s(u', v') = s(c, y) := by
        dsimp [y]; split_ifs with hcu
        · subst hcu; rfl
        · have : c = v' := by
            simp only [mem_insert_iff, mem_singleton_iff] at hc2
            exact hc2.resolve_left hcu
          subst this; exact Sym2.eq_swap
      exact e1.trans (heqxy ▸ e2.symm)
    have e1 : openSegment ℝ (pts4 u) (pts4 v) = openSegment ℝ (pts4 c) (pts4 x) := by
      dsimp [x]; split_ifs with hcu
      · subst hcu; rfl
      · have : c = v := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc1
          exact hc1.resolve_left hcu
        subst this; exact openSegment_symm _ _ _
    have e2 : openSegment ℝ (pts4 u') (pts4 v') = openSegment ℝ (pts4 c) (pts4 y) := by
      dsimp [y]; split_ifs with hcu
      · subst hcu; rfl
      · have : c = v' := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc2
          exact hc2.resolve_left hcu
        subst this; exact openSegment_symm _ _ _
    rw [e1, e2]
    exact openSegment_star_disjoint hx hy hxy
  · push Not at hshare
    have hdisj : Disjoint ({u, v} : Set (Fin 4)) {u', v'} := by
      rw [disjoint_iff_inter_eq_empty]; simpa using hshare
    exact openSegment_pts4_disjoint_complementary huv huv' hne' hdisj

/-- Every finite simple graph on at most four vertices is planar.

This is proved by a straight-line drawing with vertices at
`(0,0)`, `(2,0)`, `(0,2)`, `(1,1/2)` (triangle plus interior point) and edges as segments,
fed to `Drawing.ofVertexAndEdgePaths`. -/
theorem planar_of_vertexSet_encard_le_four [G.Finite] [G.Simple]
    (hG : V(G).encard ≤ 4) : G.Planar := by
  have : Fintype V(G) := Fintype.ofFinite _
  have hcard : Fintype.card V(G) ≤ 4 := by
    have heq : V(G).encard = (Fintype.card V(G) : ℕ∞) := by
      rw [Set.encard_eq_coe_toFinset_card, Set.toFinset_card]
    have : ((Fintype.card V(G) : ℕ) : ℕ∞) ≤ 4 := by rwa [← heq]
    exact Nat.cast_le.mp this
  let ι : V(G) ↪ Fin 4 :=
    (Fintype.equivFin V(G)).toEmbedding.trans (Fin.castLEEmb hcard)
  set vertex : V(G) → Plane := pts4 ∘ ι
  have hv : Injective vertex := pts4_injective.comp ι.injective
  have hne : ∀ e : E(G), edgeSource e ≠ edgeTarget e := by
    intro e heq
    exact (isLink_edgeSource_edgeTarget e).ne (congrArg Subtype.val heq)
  set edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)) :=
    fun e => Path.segment (vertex (edgeSource e)) (vertex (edgeTarget e))
  refine ⟨Drawing.ofVertexAndEdgePaths vertex hv edge ?_ ?_ ?_⟩
  · intro e _ _ _ _ heq
    exact Path.segment_injective_of_ne (hv.ne (hne e)) heq
  · intro e
    rw [Path.interior_segment]
    refine disjoint_left.mpr ?_
    rintro z hz ⟨w, rfl⟩
    have hij : ι (edgeSource e) ≠ ι (edgeTarget e) := ι.injective.ne (hne e)
    have hz' : pts4 (ι w) ∈
        openSegment ℝ (pts4 (ι (edgeSource e))) (pts4 (ι (edgeTarget e))) := by
      simpa [vertex] using hz
    by_cases h1 : ι w = ι (edgeSource e)
    · rw [h1] at hz'
      exact hij (pts4_injective (left_mem_openSegment_iff.mp hz'))
    · by_cases h2 : ι w = ι (edgeTarget e)
      · rw [h2] at hz'
        exact hij (pts4_injective (right_mem_openSegment_iff.mp hz'))
      · exact not_mem_openSegment_pts4 hij h1 h2 hz'
  · intro e f hef
    rw [Path.interior_segment, Path.interior_segment]
    have hij : ι (edgeSource e) ≠ ι (edgeTarget e) := ι.injective.ne (hne e)
    have hkl : ι (edgeSource f) ≠ ι (edgeTarget f) := ι.injective.ne (hne f)
    have hends : G.ends e ≠ G.ends f := (ends_injective G).ne hef
    have hne_sym : s(ι (edgeSource e), ι (edgeTarget e)) ≠
        s(ι (edgeSource f), ι (edgeTarget f)) := by
      intro heq
      apply hends
      have he : G.ends e = s(edgeSource e, edgeTarget e) :=
        (isLink_edgeSource_edgeTarget e).ends_eq
      have hf : G.ends f = s(edgeSource f, edgeTarget f) :=
        (isLink_edgeSource_edgeTarget f).ends_eq
      refine (Sym2.map.injective ι.injective) ?_
      simpa [he, hf, Sym2.map_mk] using heq
    simpa [vertex] using openSegment_pts4_disjoint hij hkl hne_sym


/-! ### Kuratowski obstructions -/

/- **Rejected route** (Status.md §11.2). `Drawing.exists_plDrawing` / `Planar.plPlanar` are proved
(`PLReduction.lean`). Assume `not_alternating_crosscut` (`ThetaCurve.lean`) as proved (formalisation
helper owns the θ-cover bridge). Still not a tactic fill: there is no named Lean bridge from a
`PLDrawing` of `CompleteGraph 5` to the polygon `J` on vertices `1,2,3,4` and the two crosscut arcs
of §11.2 — escalate that scaffolding. -/
/-- The complete graph on five vertices is not planar. -/
theorem not_planar_completeGraph_five : ¬ (CompleteGraph 5).Planar := by
  sorry

/- **Rejected route** (Status.md §11.3). Same as `not_planar_completeGraph_five`: PL reduction is
in, θ/alternating assumed; missing named bridge from a `PLDrawing` of `CompleteBipartiteGraph 3 3`
to the 4-cycle polygon and through-vertex arcs `A`, `B` of §11.3. -/
/-- The complete bipartite graph with two parts of size three is not planar. -/
theorem not_planar_completeBipartiteGraph_three_three :
    ¬ (CompleteBipartiteGraph 3 3).Planar := by
  sorry

/- **Rejected route** (Status.md §11.4 →). Local proof is
`fun h ↦ not_planar_completeGraph_five (hG.isTopologicalMinor h)`, blocked on
`IsDrawable.isTopologicalMinor` (`:670`, `sorry`) and the K₅ nonplanarity lemma above. -/
/-- A planar graph has no topological `K₅`. -/
theorem Planar.not_isTopologicalMinor_completeGraph_five (hG : G.Planar) :
    ¬ (CompleteGraph 5).IsTopologicalMinor G := by
  sorry

/- **Rejected route** (Status.md §11.4 →). Same shape as the `K₅` case:
`fun h ↦ not_planar_completeBipartiteGraph_three_three (hG.isTopologicalMinor h)`, blocked on
`IsDrawable.isTopologicalMinor` (`:670`) and `not_planar_completeBipartiteGraph_three_three`. -/
/-- A planar graph has no topological `K₃,₃`. -/
theorem Planar.not_isTopologicalMinor_completeBipartiteGraph_three_three
    (hG : G.Planar) :
    ¬ (CompleteBipartiteGraph 3 3).IsTopologicalMinor G := by
  sorry

end

end Graph
