import Matroid.Graph.Degree.Max
import Matroid.Graph.Degree.Basic
import Matroid.Graph.Minor.Defs
import Matroid.Graph.Planarity.Realization.Subgraph
import Matroid.Graph.TopologicalMinor
import Matroid.Graph.Simple
import Mathlib.Analysis.Convex.PathConnected
import Mathlib.Analysis.Convex.Segment
import Mathlib.LinearAlgebra.LinearIndependent.Basic
import Mathlib.Tactic.FinCases
-- import Mathlib.Tactic.Linarith
-- import Mathlib.Tactic.NormNum
-- import Mathlib.Tactic.Ring

/-!
# Drawings of graphs

This file defines a drawing of a graph in an arbitrary topological space to be a continuous
injection from the weak realization of the graph. It also records the construction and transport
statements needed for the topological formulation of Kuratowski's theorem.

The plane-specific part of the API is deliberately small. The difficult local topology used to
split a contracted vertex is hidden behind
`Graph.Drawing.planar_of_contract_of_facial_cycle_two_paths`.

## Main definitions

- `Graph.Drawing`: a continuous injection from the weak realization of a graph.
- `Graph.IsDrawable`: existence of a drawing in a specified topological space.
- `Graph.Planar`: existence of a drawing in the Euclidean plane.
- `Graph.Drawing.Face`: a connected component of the complement of a drawing.
- `Graph.Drawing.IsFacialSubgraph`: a subgraph whose drawing is the frontier of a face.

## Main statements

- `Graph.Drawing.ofVertexAndEdgePaths`: construct a drawing from pairwise internally disjoint edge
  paths.
- `Graph.Drawing.restrict`: restrict a drawing to a subgraph.
- `Graph.Drawing.exists_facial_cycle_of_delete_vertex`: deleting a vertex of a 3-connected plane
  drawing exposes its neighbors on a facial cycle.
- `Graph.Drawing.planar_of_contract_of_facial_cycle_two_paths`: split a contracted vertex when
  the two sets of neighbors occur on two sides of a facial cycle.
- `Graph.Planar.isTopologicalMinor`: planarity is inherited by topological minors.

## Implementation notes

`Graph.Drawing` contains only continuity and injectivity. Compactness, separation, simplicity, and
finiteness are not part of the definition.

## Tags

graph drawing, graph embedding, planar graph, Kuratowski theorem
-/

open Function Set Topology
open scoped unitInterval Convex

namespace Graph

noncomputable section

universe u v w

variable {α β γ δ : Type*} {G H : Graph α β} {K : Graph γ δ} {e : β} {u v : α}
variable {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]

/-- A drawing of `G` in `X` is a continuous injection from the weak realization of `G` to `X`. -/
structure Drawing (G : Graph α β) (X : Type u) [TopologicalSpace X] extends
    C(Realization G, X), Realization G ↪ X

-- This parent projection is generated by the `extends` command.
attribute [nolint docBlame] Drawing.toEmbedding

namespace Drawing

variable {D D' : Drawing G X}

instance : FunLike (Drawing G X) (Realization G) X where
  coe D := D.toContinuousMap
  coe_injective D₁ D₂ h := by
    cases D₁
    cases D₂
    simpa using h

instance : ContinuousMapClass (Drawing G X) (Realization G) X where
  map_continuous D := D.toContinuousMap.continuous

instance : EmbeddingLike (Drawing G X) (Realization G) X where
  injective' D := D.toEmbedding.injective

@[ext]
theorem ext {D₁ D₂ : Drawing G X} (h : ∀ x, D₁ x = D₂ x) : D₁ = D₂ :=
  DFunLike.coe_injective <| funext h

@[simp]
lemma coe_toContinuousMap (D : Drawing G X) : ⇑D.toContinuousMap = D := rfl

/-- A drawing is continuous. -/
lemma continuous (D : Drawing G X) : Continuous D :=
  D.toContinuousMap.continuous

/-- A drawing is injective. -/
lemma injective (D : Drawing G X) : Injective D :=
  D.toEmbedding.injective

/-- The point assigned by a drawing to a vertex. -/
def vertex (D : Drawing G X) (x : V(G)) : X :=
  D (vertexMk x)

/-- The path assigned by a drawing to an edge. -/
noncomputable def edgePath (D : Drawing G X) (e : E(G)) :
    Path (D.vertex (edgeSource e)) (D.vertex (edgeTarget e)) :=
  (G.edgePath e).map D.continuous

/-- The open image of a path, with both endpoints omitted. -/
def pathInterior {x y : X} (P : Path x y) : Set X :=
  P '' Ioo (0 : unitInterval) 1

/-- The image of the realization under a drawing. -/
def support (D : Drawing G X) : Set X :=
  range D

@[simp]
lemma vertex_mem_support (D : Drawing G X) (x : V(G)) : D.vertex x ∈ D.support :=
  ⟨vertexMk x, rfl⟩

lemma edgePath_range_subset_support (D : Drawing G X) (e : E(G)) :
    range (D.edgePath e) ⊆ D.support := by
  rintro _ ⟨t, rfl⟩
  refine ⟨G.edgePath e t, rfl⟩

/-- Distinct vertices have distinct images in a drawing. -/
lemma vertex_injective (D : Drawing G X) : Injective D.vertex :=
  fun _ _ hxy ↦ vertexMk_inj.mp <| D.injective hxy

@[simp]
lemma edgePath_apply (D : Drawing G X) (e : E(G)) (t : I) : D.edgePath e t = D (G.edgePath e t) :=
  rfl

/-- Every point of the support is either a vertex image or lies on some edge path. -/
lemma support_eq (D : Drawing G X) :
    D.support = range D.vertex ∪ ⋃ e : E(G), range (D.edgePath e) := by
  ext x
  simp only [support, mem_range, mem_union, mem_iUnion]
  constructor
  · rintro ⟨y, rfl⟩
    induction y using Realization.ind with | h a =>
    match a with
    | .inl v => exact Or.inl ⟨v, rfl⟩
    | .inr ⟨e, t⟩ => exact Or.inr ⟨e, t, by simp [edgePath_apply]⟩
  · rintro (⟨v, rfl⟩ | ⟨e, t, rfl⟩)
    · exact ⟨vertexMk v, rfl⟩
    · exact ⟨G.edgePath e t, rfl⟩

/-- The open part of each edge path is injectively parametrized. -/
lemma edgePath_injOn_Ioo (D : Drawing G X) (e : E(G)) :
    InjOn (D.edgePath e) (Ioo (0 : unitInterval) 1) :=
  fun _ ht₁ _ _ heq ↦ edgePath_inj_of_mem_Ioo (mod_cast ht₁) <| D.injective heq

/-- The open part of an edge is disjoint from all vertex images. -/
lemma pathInterior_edgePath_disjoint_vertex (D : Drawing G X) (e : E(G)) :
    Disjoint (pathInterior (D.edgePath e)) (range D.vertex) := by
  refine disjoint_left.mpr ?_
  rintro _ ⟨t, ht, rfl⟩ ⟨v, hv⟩
  exact vertexMk_not_mem_edgePath_Ioo v e ⟨t, ht, D.injective hv.symm⟩

/-- The open parts of distinct edges are disjoint. -/
lemma pathInterior_edgePath_disjoint (D : Drawing G X) {e f : E(G)} (hef : e ≠ f) :
    Disjoint (pathInterior (D.edgePath e)) (pathInterior (D.edgePath f)) := by
  refine disjoint_left.mpr ?_
  rintro _ ⟨t, ht, rfl⟩ ⟨s, hs, heq⟩
  exact ((disjoint_edgePath_Ioo_iff e f).mpr hef).notMem_of_mem_left ⟨t, ht, rfl⟩
    ⟨s, hs, D.injective heq⟩

/-- The support of a drawing of a finite graph is compact. -/
lemma support_isCompact [G.Finite] (D : Drawing G X) : IsCompact D.support :=
  isCompact_range D.continuous

/-- In a Hausdorff space, the support of a drawing of a finite graph is closed. -/
lemma support_isClosed [G.Finite] [T2Space X] (D : Drawing G X) : IsClosed D.support :=
  D.support_isCompact.isClosed

/-- Postcompose a drawing with a continuous injection of ambient spaces. -/
def postcomp (D : Drawing G X) (f : C(X, Y)) (hf : Injective f) : Drawing G Y where
  toContinuousMap := f.comp D.toContinuousMap
  inj' := hf.comp D.injective

@[simp]
lemma postcomp_apply (D : Drawing G X) (f : C(X, Y)) (hf : Injective f)
    (x : Realization G) : D.postcomp f hf x = f (D x) :=
  rfl

/-! ### Constructors -/

/-- Construct a drawing from a map on the pre-realization that identifies exactly the points
identified by the realization quotient. -/
noncomputable def ofPreRealization (f : C(G.PreRealization, X))
    (map_eq_of_glueRel : ∀ a b, G.glueRel a b → f a = f b)
    (glueRel_of_map_eq : ∀ a b, f a = f b → G.glueRel a b) : Drawing G X where
  toContinuousMap :=
    ⟨Quotient.lift f map_eq_of_glueRel, continuous_quot_lift map_eq_of_glueRel f.continuous⟩
  inj' x y h := by
    induction x using Realization.ind with | h a =>
    induction y using Realization.ind with | h b =>
    exact Realization.mk_eq_mk.mpr (glueRel_of_map_eq a b h)

/-- Construct a drawing by assigning distinct points to vertices and internally disjoint paths to
edges.

The hypotheses allow loops and parallel edges. For a loop, the two endpoints of its path agree,
as prescribed by `edgeSource` and `edgeTarget`; only the open interval is required to be
injective. -/
noncomputable def preRealizationMapOfPaths (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) :
    C(G.PreRealization, X) :=
  ⟨Sum.elim vertex fun p ↦ edge p.1 p.2,
    continuous_sum_dom.mpr ⟨continuous_of_discreteTopology,
      continuous_sigma fun e ↦ (edge e).continuous⟩⟩

@[simp]
lemma preRealizationMapOfPaths_inl (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) (x : V(G)) :
    preRealizationMapOfPaths vertex edge (Sum.inl x) = vertex x := rfl

@[simp]
lemma preRealizationMapOfPaths_inr (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (e : E(G)) (t : unitInterval) :
    preRealizationMapOfPaths vertex edge (Sum.inr ⟨e, t⟩) = edge e t := rfl

/-- The endpoints of the paths are where the realization glues, so the map respects the relation.
This direction needs no hypothesis: it is `Path.source` and `Path.target`. -/
theorem map_eq_of_glueRel_preRealizationMapOfPaths (vertex : V(G) → X)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e))) :
    ∀ a b, G.glueRel a b →
      preRealizationMapOfPaths vertex edge a = preRealizationMapOfPaths vertex edge b := by
  intro a b h
  induction h with
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ h₁ h₂ => exact h₁.trans h₂
  | rel x y hxy =>
    match x, y with
    | .inr _, _ =>
      simp [glueRelAux] at hxy
    | .inl u, .inl v =>
      obtain rfl := (glueRelAux_inl_inl_iff ..).mp hxy
      rfl
    | .inl u, .inr ⟨e, t⟩ =>
      obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := (glueRelAux_inl_inr_iff ..).mp hxy
      · simp [Path.source]
      · simp [Path.target]

/-- Conversely, the map identifies *only* what the realization glues. This is where all four
hypotheses are used, and it is the whole mathematical content of `ofVertexAndEdgePaths`. -/
theorem glueRel_of_map_eq_preRealizationMapOfPaths (vertex : V(G) → X)
    (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (pathInterior (edge e)) (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f →
      Disjoint (pathInterior (edge e)) (pathInterior (edge f))) :
    ∀ a b, preRealizationMapOfPaths vertex edge a = preRealizationMapOfPaths vertex edge b →
      G.glueRel a b := by
  intro a b h
  match a, b with
  | .inl u, .inl v =>
    exact (glueRel_inl_inl_iff u v).mpr (vertex_injective (by simpa using h))
  | .inl u, .inr ⟨e, t⟩ =>
    have hvt : vertex u = edge e t := by simpa using h
    rcases eq_or_ne t 0 with rfl | ht0
    · exact (glueRel_inl_inr_iff u e 0).mpr <|
        .inl ⟨rfl, vertex_injective (by simpa [Path.source] using hvt)⟩
    rcases eq_or_ne t 1 with rfl | ht1
    · exact (glueRel_inl_inr_iff u e 1).mpr <|
        .inr ⟨rfl, vertex_injective (by simpa [Path.target] using hvt)⟩
    · exact ((edge_interior_disjoint_vertex e).notMem_of_mem_left
        ⟨t, ⟨unitInterval.pos_iff_ne_zero.mpr ht0, unitInterval.lt_one_iff_ne_one.mpr ht1⟩, rfl⟩
        ⟨u, hvt⟩).elim
  | .inr ⟨e, t⟩, .inl v =>
    have hvt : edge e t = vertex v := by simpa using h
    rcases eq_or_ne t 0 with rfl | ht0
    · exact (glueRel_inr_inl_iff e 0 v).mpr <|
        .inl ⟨rfl, vertex_injective (by simpa [Path.source] using hvt.symm)⟩
    rcases eq_or_ne t 1 with rfl | ht1
    · exact (glueRel_inr_inl_iff e 1 v).mpr <|
        .inr ⟨rfl, vertex_injective (by simpa [Path.target] using hvt.symm)⟩
    · exact ((edge_interior_disjoint_vertex e).notMem_of_mem_left
        ⟨t, ⟨unitInterval.pos_iff_ne_zero.mpr ht0, unitInterval.lt_one_iff_ne_one.mpr ht1⟩, rfl⟩
        ⟨v, hvt.symm⟩).elim
  | .inr ⟨e₁, t₁⟩, .inr ⟨e₂, t₂⟩ =>
    have heq : edge e₁ t₁ = edge e₂ t₂ := by simpa using h
    rcases eq_or_ne t₁ 0 with rfl | ht₁₀
    · rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · have hv : edgeSource e₁ = edgeSource e₂ :=
          vertex_injective (by simpa [Path.source] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 0 0).mpr <| Or.inr ⟨edgeSource e₁, by simp, ?_⟩
        simp [hv]
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · have hv : edgeSource e₁ = edgeTarget e₂ :=
          vertex_injective (by simpa [Path.source, Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 0 1).mpr <| Or.inr ⟨edgeSource e₁, by simp, ?_⟩
        simp [hv]
      · exact ((edge_interior_disjoint_vertex e₂).notMem_of_mem_left
          ⟨t₂, ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩, rfl⟩
          ⟨edgeSource e₁, by simpa [Path.source] using heq⟩).elim
    rcases eq_or_ne t₁ 1 with rfl | ht₁₁
    · rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · have hv : edgeTarget e₁ = edgeSource e₂ :=
          vertex_injective (by simpa [Path.source, Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 1 0).mpr <| Or.inr ⟨edgeTarget e₁, by simp, ?_⟩
        simp [hv]
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · have hv : edgeTarget e₁ = edgeTarget e₂ :=
          vertex_injective (by simpa [Path.target] using heq)
        refine (glueRel_inr_inr_iff e₁ e₂ 1 1).mpr <| Or.inr ⟨edgeTarget e₁, by simp, ?_⟩
        simp [hv]
      · exact ((edge_interior_disjoint_vertex e₂).notMem_of_mem_left
          ⟨t₂, ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩, rfl⟩
          ⟨edgeTarget e₁, by simpa [Path.target] using heq⟩).elim
    · have ht₁ : t₁ ∈ Ioo (0 : I) 1 :=
        ⟨unitInterval.pos_iff_ne_zero.mpr ht₁₀, unitInterval.lt_one_iff_ne_one.mpr ht₁₁⟩
      rcases eq_or_ne t₂ 0 with rfl | ht₂₀
      · exact ((edge_interior_disjoint_vertex e₁).notMem_of_mem_left ⟨t₁, ht₁, rfl⟩
          ⟨edgeSource e₂, by simpa [Path.source] using heq.symm⟩).elim
      rcases eq_or_ne t₂ 1 with rfl | ht₂₁
      · exact ((edge_interior_disjoint_vertex e₁).notMem_of_mem_left ⟨t₁, ht₁, rfl⟩
          ⟨edgeTarget e₂, by simpa [Path.target] using heq.symm⟩).elim
      · have ht₂ : t₂ ∈ Ioo (0 : I) 1 :=
          ⟨unitInterval.pos_iff_ne_zero.mpr ht₂₀, unitInterval.lt_one_iff_ne_one.mpr ht₂₁⟩
        obtain rfl | he := eq_or_ne e₁ e₂
        · exact (glueRel_inr_inr_iff e₁ e₁ t₁ t₂).mpr <|
            Or.inl ⟨rfl, edge_injective e₁ ht₁ ht₂ heq⟩
        · exact ((edge_interior_disjoint e₁ e₂ he).notMem_of_mem_left
            ⟨t₁, ht₁, rfl⟩ ⟨t₂, ht₂, heq.symm⟩).elim

noncomputable def ofVertexAndEdgePaths
    (vertex : V(G) → X) (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (pathInterior (edge e)) (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f →
      Disjoint (pathInterior (edge e)) (pathInterior (edge f))) :
    Drawing G X :=
  ofPreRealization (preRealizationMapOfPaths vertex edge)
    (map_eq_of_glueRel_preRealizationMapOfPaths vertex edge)
    (glueRel_of_map_eq_preRealizationMapOfPaths vertex vertex_injective edge edge_injective
      edge_interior_disjoint_vertex edge_interior_disjoint)

variable {vertex : V(G) → X} {edge : ∀ e : E(G), Path (vertex (edgeSource e))
  (vertex (edgeTarget e))} {hv : Injective vertex} {he : ∀ e, InjOn (edge e) (Ioo (0 : I) 1)}
  {hev : ∀ e, Disjoint (pathInterior (edge e)) (range vertex)}
  {hee : ∀ e f, e ≠ f → Disjoint (pathInterior (edge e)) (pathInterior (edge f))}

@[simp]
lemma ofVertexAndEdgePaths_vertex (x : V(G)) :
    (ofVertexAndEdgePaths vertex hv edge he hev hee).vertex x = vertex x := rfl

@[simp]
lemma ofVertexAndEdgePaths_edgePath_apply (e : E(G)) (t : unitInterval) :
    (ofVertexAndEdgePaths vertex hv edge he hev hee).edgePath e t = edge e t := rfl

lemma range_edgePath_ofVertexAndEdgePaths (e : E(G)) :
    range ((ofVertexAndEdgePaths vertex hv edge he hev hee).edgePath e) = range (edge e) := rfl

/-- The empty graph has a drawing in every topological space, including the empty space. -/
noncomputable def bot (X : Type u) [TopologicalSpace X] : Drawing (⊥ : Graph α β) X :=
  ofPreRealization ⟨fun a ↦ isEmptyElim a, continuous_of_discreteTopology⟩
    (fun a ↦ isEmptyElim a) (fun a ↦ isEmptyElim a)

/-! ### Restriction and transport -/

/-- Restrict a drawing to a subgraph. -/
def restrict (D : Drawing G X) (h : H ≤ G) : Drawing H X where
  toContinuousMap := D.toContinuousMap.comp h.realizationContinuousMap
  inj' := D.injective.comp h.RealizationEmbedding_isEmbedding.injective

@[simp]
lemma restrict_apply (D : Drawing G X) (h : H ≤ G) (x : Realization H) :
    D.restrict h x = D (h.RealizationEmbedding x) := rfl

/-! Restriction changes neither the position of a vertex nor the image of an edge. The two
`edgeSource`/`edgeTarget` statements are the ones that would fail if the orientation of an edge
were chosen per graph rather than determined by its ends; they hold because `ArbRel` fixes one
linear order per *type*, so `IsSubgraph.source` and `IsSubgraph.target` are available. -/

@[simp]
lemma restrict_vertex (D : Drawing G X) (h : H ≤ G) (x : V(H)) :
    (D.restrict h).vertex x = D.vertex ⟨x.1, vertexSet_mono h x.2⟩ := by
  simp [vertex, restrict_apply]

lemma restrict_vertex_edgeSource (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    (D.restrict h).vertex (edgeSource e) = D.vertex (edgeSource ⟨e.1, edgeSet_mono h e.2⟩) := by
  rw [restrict_vertex]
  congr 1
  ext
  simp [edgeSource, h.source]

lemma restrict_vertex_edgeTarget (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    (D.restrict h).vertex (edgeTarget e) = D.vertex (edgeTarget ⟨e.1, edgeSet_mono h e.2⟩) := by
  rw [restrict_vertex]
  congr 1
  ext
  simp [edgeTarget, h.target]

@[simp]
lemma range_edgePath_restrict (D : Drawing G X) (h : H ≤ G) (e : E(H)) :
    range ((D.restrict h).edgePath e) = range (D.edgePath ⟨e.1, edgeSet_mono h e.2⟩) := by
  ext x
  simp only [mem_range]
  refine ⟨fun ⟨t, ht⟩ ↦ ⟨t, ?_⟩, fun ⟨t, ht⟩ ↦ ⟨t, ?_⟩⟩ <;>
    rw [← ht, edgePath_apply, edgePath_apply, restrict_apply, h.RealizationEmbedding_edgePath]

end Drawing

namespace Iso

open TopologicalModel unitInterval

/-- The image of a vertex under a graph isomorphism, as a subtype. -/
noncomputable abbrev vert (F : Iso K G) (x : V(K)) : V(G) :=
  isoVert F x

/-- The image of an edge under a graph isomorphism, as a subtype. -/
noncomputable abbrev edge (F : Iso K G) (e : E(K)) : E(G) :=
  isoEdge F e

lemma isLink_vert_edge (F : Iso K G) (e : E(K)) :
    G.IsLink (F.edge e) (F.vert (edgeSource e)) (F.vert (edgeTarget e)) :=
  F.map_isLink (isLink_edgeSource_edgeTarget e) (isoEdge_spec F e)
    (isoVert_spec F _) (isoVert_spec F _)

/-- Whether `F` sends the preferred orientation of `e` to that of its image. -/
abbrev sameOrientation (F : Iso K G) (e : E(K)) : Prop :=
  F.vert (edgeSource e) = edgeSource (F.edge e)

lemma sameOrientation_or_swap (F : Iso K G) (e : E(K)) :
    F.sameOrientation e ∨
      (F.vert (edgeSource e) = edgeTarget (F.edge e) ∧
        F.vert (edgeTarget e) = edgeSource (F.edge e)) := by
  obtain ⟨h₁, h₂⟩ | ⟨h₁, h₂⟩ :=
    (isLink_edgeSource_edgeTarget (F.edge e)).eq_and_eq_or_eq_and_eq (F.isLink_vert_edge e)
  · exact Or.inl <| Subtype.ext h₁.symm
  · exact Or.inr ⟨Subtype.ext h₂.symm, Subtype.ext h₁.symm⟩

lemma vert_edgeTarget_of_sameOrientation (F : Iso K G) {e : E(K)} (h : F.sameOrientation e) :
    F.vert (edgeTarget e) = edgeTarget (F.edge e) := by
  obtain ⟨_, h₂⟩ | ⟨h₁, h₂⟩ :=
    (isLink_edgeSource_edgeTarget (F.edge e)).eq_and_eq_or_eq_and_eq (F.isLink_vert_edge e)
  · exact Subtype.ext h₂.symm
  · have hsrc : F.vert (edgeSource e) = F.vert (edgeTarget e) := by
      rw [h, Subtype.ext_iff.mpr h₁]
    exact hsrc.symm.trans (Subtype.ext h₂.symm)

lemma vert_of_not_sameOrientation (F : Iso K G) {e : E(K)} (h : ¬ F.sameOrientation e) :
    F.vert (edgeSource e) = edgeTarget (F.edge e) ∧
      F.vert (edgeTarget e) = edgeSource (F.edge e) :=
  (F.sameOrientation_or_swap e).resolve_left h

/-- Reparametrization of the unit interval along `e`, flipping if `F` reverses orientation. -/
noncomputable def orient (F : Iso K G) (e : E(K)) : I → I :=
  open Classical in fun t ↦ if F.sameOrientation e then t else σ t

lemma continuous_orient (F : Iso K G) (e : E(K)) : Continuous (F.orient e) := by
  classical
  by_cases h : F.sameOrientation e
  · convert continuous_id (X := I)
    ext t
    simp [orient, if_pos h]
  · convert continuous_symm
    ext t
    simp [orient, if_neg h]

/-- The induced map on pre-realizations. -/
noncomputable def preRealizationMap (F : Iso K G) : C(K.PreRealization, G.PreRealization) where
  toFun
    | .inl v => .inl (F.vert v)
    | .inr ⟨e, t⟩ => .inr ⟨F.edge e, F.orient e t⟩
  continuous_toFun := continuous_sum_dom.mpr ⟨continuous_of_discreteTopology,
    continuous_sigma_iff.mpr fun e ↦ continuous_inr.comp <|
      continuous_sigmaMk.comp (F.continuous_orient e)⟩

lemma preRealizationMap_glueRel (F : Iso K G) ⦃a b : K.PreRealization⦄
    (h : K.glueRel a b) : G.glueRel (F.preRealizationMap a) (F.preRealizationMap b) := by
  classical
  induction h with
  | refl => rfl
  | symm _ _ _ ih => exact Setoid.symm ih
  | trans _ _ _ _ _ h₁ h₂ => exact Setoid.trans h₁ h₂
  | rel x y hxy =>
    match x, y with
    | .inr _, _ =>
      simp [glueRelAux] at hxy
    | .inl u, .inl v =>
      obtain rfl := (glueRelAux_inl_inl_iff ..).mp hxy
      rfl
    | .inl u, .inr ⟨e, t⟩ =>
      obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := (glueRelAux_inl_inr_iff ..).mp hxy
      · by_cases hori : F.sameOrientation e
        · convert (glueRel_inl_inr_iff (edgeSource (F.edge e)) (F.edge e) 0).mpr
            (.inl ⟨rfl, rfl⟩) using 1
          · simpa [preRealizationMap] using hori
          · simp [preRealizationMap, orient, if_pos hori]
        · obtain ⟨hs, _⟩ := F.vert_of_not_sameOrientation hori
          convert (glueRel_inl_inr_iff (edgeTarget (F.edge e)) (F.edge e) 1).mpr
            (.inr ⟨rfl, rfl⟩) using 1
          · simpa [preRealizationMap] using hs
          · simp [preRealizationMap, orient, if_neg hori]
      · by_cases hori : F.sameOrientation e
        · convert (glueRel_inl_inr_iff (edgeTarget (F.edge e)) (F.edge e) 1).mpr
            (.inr ⟨rfl, rfl⟩) using 1
          · simpa [preRealizationMap] using F.vert_edgeTarget_of_sameOrientation hori
          · simp [preRealizationMap, orient, if_pos hori]
        · obtain ⟨_, ht⟩ := F.vert_of_not_sameOrientation hori
          convert (glueRel_inl_inr_iff (edgeSource (F.edge e)) (F.edge e) 0).mpr
            (.inl ⟨rfl, rfl⟩) using 1
          · simpa [preRealizationMap] using ht
          · simp [preRealizationMap, orient, if_neg hori]

lemma vert_symm_vert (F : Iso K G) (x : V(K)) : F.symm.vert (F.vert x) = x := by
  ext
  change (F.vertMap.symm (F.vert x).val).get _ = x.val
  have hx : F.vertMap.symm (F.vert x).val = some x.val :=
    (F.vertMap.eq_some_iff).mpr (isoVert_spec F x)
  simp [hx]

lemma vert_vert_symm (F : Iso K G) (y : V(G)) : F.vert (F.symm.vert y) = y := by
  ext
  change (F.vertMap (F.symm.vert y).val).get _ = y.val
  have hy : F.vertMap (F.symm.vert y).val = some y.val :=
    (F.vertMap.eq_some_iff).mp (isoVert_spec F.symm y)
  simp [hy]

lemma edge_symm_edge (F : Iso K G) (e : E(K)) : F.symm.edge (F.edge e) = e := by
  ext
  change (F.edgeMap.symm (F.edge e).val).get _ = e.val
  have he : F.edgeMap.symm (F.edge e).val = some e.val :=
    (F.edgeMap.eq_some_iff).mpr (isoEdge_spec F e)
  simp [he]

lemma edge_edge_symm (F : Iso K G) (e : E(G)) : F.edge (F.symm.edge e) = e := by
  ext
  change (F.edgeMap (F.symm.edge e).val).get _ = e.val
  have he : F.edgeMap (F.symm.edge e).val = some e.val :=
    (F.edgeMap.eq_some_iff).mp (isoEdge_spec F.symm e)
  simp [he]

lemma sameOrientation_symm (F : Iso K G) {e : E(K)} (h : F.sameOrientation e) :
    F.symm.sameOrientation (F.edge e) := by
  unfold sameOrientation at h ⊢
  simpa [vert_symm_vert, edge_symm_edge] using congrArg F.symm.vert h.symm

lemma not_sameOrientation_symm (F : Iso K G) {e : E(K)} (h : ¬ F.sameOrientation e) :
    ¬ F.symm.sameOrientation (F.edge e) := by
  intro hs
  unfold sameOrientation at hs
  have hs' : F.symm.vert (edgeSource (F.edge e)) = edgeSource e := by
    simpa [edge_symm_edge] using hs
  have : F.vert (edgeSource e) = edgeSource (F.edge e) := by
    simpa [vert_vert_symm] using congrArg F.vert hs'.symm
  exact h this

lemma sameOrientation_edge_symm (F : Iso K G) (e : E(G)) :
    F.sameOrientation (F.symm.edge e) ↔ F.symm.sameOrientation e := by
  refine ⟨fun h ↦ ?_, fun h ↦ ?_⟩
  · unfold sameOrientation at h ⊢
    have h' : F.vert (edgeSource (F.symm.edge e)) = edgeSource e := by
      simpa [edge_edge_symm] using h
    simpa [vert_symm_vert] using congrArg F.symm.vert h'.symm
  · unfold sameOrientation at h ⊢
    have := congrArg F.vert h
    simpa [vert_vert_symm, edge_edge_symm] using this.symm

lemma orient_symm_orient (F : Iso K G) (e : E(K)) (t : I) :
    F.symm.orient (F.edge e) (F.orient e t) = t := by
  classical
  by_cases h : F.sameOrientation e
  · simp [orient, if_pos h, if_pos (F.sameOrientation_symm h)]
  · simp [orient, if_neg h, if_neg (F.not_sameOrientation_symm h), symm_symm]

lemma orient_orient_symm (F : Iso K G) (e : E(G)) (t : I) :
    F.orient (F.symm.edge e) (F.symm.orient e t) = t := by
  classical
  by_cases h : F.symm.sameOrientation e
  · simp [orient, if_pos h, if_pos ((F.sameOrientation_edge_symm e).mpr h)]
  · simp [orient, if_neg h, if_neg (mt (F.sameOrientation_edge_symm e).mp h), symm_symm]

lemma preRealizationMap_symm_comp (F : Iso K G) (x : K.PreRealization) :
    F.symm.preRealizationMap (F.preRealizationMap x) = x := by
  match x with
  | .inl v =>
    simp only [preRealizationMap, ContinuousMap.coe_mk, vert_symm_vert]
  | .inr ⟨e, t⟩ =>
    simp only [preRealizationMap, ContinuousMap.coe_mk, edge_symm_edge, orient_symm_orient]

lemma preRealizationMap_comp_symm (F : Iso K G) (x : G.PreRealization) :
    F.preRealizationMap (F.symm.preRealizationMap x) = x := by
  match x with
  | .inl v =>
    simp only [preRealizationMap, ContinuousMap.coe_mk, vert_vert_symm]
  | .inr ⟨e, t⟩ =>
    simp only [preRealizationMap, ContinuousMap.coe_mk, edge_edge_symm, orient_orient_symm]

/-- The homeomorphism of weak realizations induced by a graph isomorphism. -/
noncomputable def realizationHomeomorph (F : Iso K G) : Realization K ≃ₜ Realization G where
  toFun := Quotient.map F.preRealizationMap F.preRealizationMap_glueRel
  invFun := Quotient.map F.symm.preRealizationMap F.symm.preRealizationMap_glueRel
  left_inv := by
    intro x
    induction x using Realization.ind with | h a =>
    exact congrArg (Realization.mk K) (F.preRealizationMap_symm_comp a)
  right_inv := by
    intro x
    induction x using Realization.ind with | h a =>
    exact congrArg (Realization.mk G) (F.preRealizationMap_comp_symm a)
  continuous_toFun := by
    rw [continuous_coinduced_dom]
    exact continuous_coinduced_rng.comp F.preRealizationMap.continuous
  continuous_invFun := by
    rw [continuous_coinduced_dom]
    exact continuous_coinduced_rng.comp F.symm.preRealizationMap.continuous

end Iso

namespace Drawing

/-- Pull a drawing back along a graph isomorphism. -/
noncomputable def ofIso (D : Drawing G X) (F : Iso K G) : Drawing K X where
  toContinuousMap :=
    { toFun := D ∘ F.realizationHomeomorph
      continuous_toFun := D.continuous.comp F.realizationHomeomorph.continuous }
  inj' := D.injective.comp F.realizationHomeomorph.injective

/-- A drawing `D'` extends `D` along the subgraph inclusion `h`. -/
def Extends (D' : Drawing G X) (D : Drawing H X) (h : H ≤ G) : Prop :=
  ∀ x, D' (h.RealizationEmbedding x) = D x

/-! ### Drawability and planarity -/

end Drawing

/-- A graph is drawable in `X` if its weak realization admits a continuous injection into `X`. -/
def IsDrawable (G : Graph α β) (X : Type u) [TopologicalSpace X] : Prop :=
  Nonempty (Drawing G X)

/-- A graph is planar if it has a drawing in the Euclidean plane. -/
def Planar (G : Graph α β) : Prop :=
  G.IsDrawable (EuclideanSpace ℝ (Fin 2))

/-- The empty graph is drawable in every topological space. -/
theorem bot_isDrawable (X : Type u) [TopologicalSpace X] :
    (⊥ : Graph α β).IsDrawable X :=
  ⟨Drawing.bot X⟩

/-- The empty graph is planar. -/
theorem bot_planar : (⊥ : Graph α β).Planar :=
  bot_isDrawable (EuclideanSpace ℝ (Fin 2))

namespace IsDrawable

/-- Drawability is inherited by subgraphs. -/
lemma anti (hG : G.IsDrawable X) (hHG : H ≤ G) : H.IsDrawable X :=
  ⟨hG.some.restrict hHG⟩

/-- Drawability is invariant under graph isomorphism. -/
lemma of_iso (hG : G.IsDrawable X) (F : Iso K G) : K.IsDrawable X :=
  ⟨hG.some.ofIso F⟩

/-- Drawability is inherited by topological minors. -/
/- **Handoff to formalisation helper.** Needs a `Drawing` of `H` from a `Drawing` of `G` along a
`TopologicalModel` / `IsTopologicalMinor`: concatenate `D.edgePath` along each route, and check
disjointness of open cells against `route_internal_disjoint` / `route_edge_disjoint`. No named
`Drawing.ofTopologicalModel` (or equivalent) exists; building it is scaffolding, not a one-line
fill from `restrict`/`ofIso`. -/
theorem isTopologicalMinor (hG : G.IsDrawable X) (hHG : H.IsTopologicalMinor G) : H.IsDrawable X := by
  sorry

end IsDrawable

namespace Planar

/-- Planarity is inherited by subgraphs. -/
lemma anti (hG : G.Planar) (hHG : H ≤ G) : H.Planar :=
  IsDrawable.anti hG hHG

/-- Planarity is invariant under graph isomorphism. -/
lemma of_iso (hG : G.Planar) (F : Iso K G) : K.Planar :=
  IsDrawable.of_iso hG F

/-- Planarity is inherited by topological minors. -/
theorem isTopologicalMinor (hG : G.Planar) (hHG : H.IsTopologicalMinor G) : H.Planar :=
  IsDrawable.isTopologicalMinor hG hHG

/- **Proof route for the two theorems below** (formalisation helper). These are not small `sorry`
fills, and the earlier note here was right that gluing is missing. But the gap splits in two, and
only the second half is ambient topology.

*(a) A missing combinator, mine to supply; no topology in it.*

    def Drawing.union (D₁ : Drawing G₁ X) (D₂ : Drawing G₂ X) (hc : G₁.Compatible G₂)
        (hsupp : D₁.support ∩ D₂.support = D₁.vertex '' {v | v.1 ∈ V(G₁) ∩ V(G₂)}) :
        Drawing (G₁ ∪ G₂) X

The argument is the `Sum` case split already written out in
`glueRel_of_map_eq_preRealizationMapOfPaths` above, one level up; build it with `ofPreRealization`.
Nothing here needs `[Finite]`, a metric, or the plane. Written once, it discharges the
`V(G₁) ∩ V(G₂) = ∅` case of the first theorem immediately: both supports are compact
(`support_isCompact`, `:154`) hence bounded, so translating `D₂` far enough separates them, and
`postcomp` takes any *continuous injection* — `fun z ↦ c • z + b` with `c ≠ 0`, continuous by
`fun_prop` and injective by `smul_right_injective` — so no homeomorphism API is needed.

*(b) A free direction at the shared vertex.* For the singleton case you need a wedge at
`D₁.vertex v` meeting `D₁.support` only at that point, into which the scaled `D₂` goes. Do **not**
route this through `DiskMinusRadii`'s sector count: in the PL category the segments through `p` are
finitely many, so all but finitely many directions are free, and
`Graph.PLDrawing.exists_radius` (`Planarity/StarLemma.lean`) keeps the rest of the support out of
a small ball. That is a strictly weaker obligation than the star lemma's exact equality; state it
separately as `exists_free_wedge` and prove it first if `exists_radius` proves expensive.

So the real prerequisites are `PLDrawing.exists_finite_support`, then `exists_radius` (or just the
weak wedge), then `Drawing.union` — none of which is Schoenflies-strength, and none of which needs
the two open closure lemmas in `DiskMinusRadii`.

*Note.* `IsForest.planar` below already calls `union_of_vertexSet_inter_subsingleton`, so it reads
as complete while resting on this chain.

**Tactic handoff (2026-08-11).** `Drawing.union` and `exists_free_wedge` are still not declared —
only described in this comment. Per the route above they are formalisation-helper deliverables
("mine to supply"). Tactic will not invent those defs; return when they exist with proof routes. -/
/-- The union of two finite planar graphs meeting in at most one vertex is planar. -/
theorem union_of_vertexSet_inter_subsingleton {G₁ G₂ : Graph α β} [G₁.Finite] [G₂.Finite]
    (h₁ : G₁.Planar) (h₂ : G₂.Planar) (hcompat : G₁.Compatible G₂)
    (hedge : Disjoint E(G₁) E(G₂)) (hvertex : (V(G₁) ∩ V(G₂)).Subsingleton) :
    (G₁ ∪ G₂).Planar := by
  sorry

/-- The union of two finite planar graphs along a common nonloop edge is planar. -/
theorem union_of_common_nonloop_edge {G₁ G₂ : Graph α β} [G₁.Finite] [G₂.Finite]
    (h₁ : G₁.Planar) (h₂ : G₂.Planar) (hcompat : G₁.Compatible G₂)
    (he₁ : G₁.IsLink e u v) (he₂ : G₂.IsLink e u v) (huv : u ≠ v)
    (hvertex : V(G₁) ∩ V(G₂) = {u, v}) (hedge : E(G₁) ∩ E(G₂) = {e}) :
    (G₁ ∪ G₂).Planar := by
  sorry

end Planar

abbrev Plane := EuclideanSpace ℝ (Fin 2)

/-- Embed a finite type into the plane along the x-axis. -/
noncomputable def embedFinite (ι : Type*) [Finite ι] : ι → Plane :=
  fun i => EuclideanSpace.single 0 (Finite.equivFin ι i : ℝ)

lemma embedFinite_injective (ι : Type*) [Finite ι] : Injective (embedFinite ι) := by
  intro a b h
  have : (Finite.equivFin ι a : ℝ) = (Finite.equivFin ι b : ℝ) := by
    simpa [embedFinite, PiLp.single_apply] using congrArg (fun v : Plane => v 0) h
  exact (Finite.equivFin ι).injective (Fin.val_injective (Nat.cast_injective this))

lemma pathInterior_segment (a b : Plane) :
    Drawing.pathInterior (Path.segment a b) = openSegment ℝ a b := by
  ext z
  constructor
  · rintro ⟨t, ht, rfl⟩
    rw [openSegment_eq_image_lineMap]
    exact ⟨t, ht, by simp [Path.segment_apply]⟩
  · rw [openSegment_eq_image_lineMap]
    rintro ⟨t, ht, rfl⟩
    exact ⟨⟨t, ht.1.le, ht.2.le⟩, ht, by simp [Path.segment_apply]⟩

/-- An edgeless finite graph is planar. -/
theorem noEdge_planar (V : Set α) (hV : V.Finite) : (Graph.noEdge V β).Planar := by
  have : (Graph.noEdge V β).Finite := (noEdge_finite V).mpr hV
  have : Finite ↑V(Graph.noEdge V β) := by
    simpa [vertexSet_noEdge] using hV.to_subtype
  refine ⟨Drawing.ofVertexAndEdgePaths (embedFinite _) (embedFinite_injective _)
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))
    (fun ed _ _ => False.elim (by
      have : ed.1 ∈ (∅ : Set β) := by simpa [edgeSet_noEdge] using ed.2
      exact this))⟩

lemma singleEdge_edgeSource_ne_edgeTarget {x y : α} (hxy : x ≠ y) (e : β)
    (f : E(Graph.singleEdge x y e)) : edgeSource f ≠ edgeTarget f := by
  intro heq
  have hlink := isLink_edgeSource_edgeTarget f
  have hf : (f : β) = e := by simpa [edgeSet_singleEdge] using f.2
  have heq' : (edgeSource f : α) = edgeTarget f := congrArg Subtype.val heq
  rw [singleEdge_isLink_iff, hf, heq'] at hlink
  obtain ⟨-, hs⟩ := hlink
  obtain ⟨h1, h2⟩ | ⟨h1, h2⟩ := Sym2.eq_iff.mp hs
  · exact hxy (h1.symm.trans h2)
  · exact hxy (h2.symm.trans h1)

/-- A nonloop edge is planar. -/
theorem singleEdge_planar {x y : α} (hxy : x ≠ y) (e : β) : (Graph.singleEdge x y e).Planar := by
  set G := Graph.singleEdge x y e
  have : Finite ↑V(G) := by
    change Finite ↑({x, y} : Set α)
    infer_instance
  set vertex : V(G) → Plane := embedFinite V(G)
  have hv : Injective vertex := embedFinite_injective _
  have hne : ∀ f : E(G), edgeSource f ≠ edgeTarget f :=
    fun f ↦ singleEdge_edgeSource_ne_edgeTarget hxy e f
  set edge : ∀ f : E(G), Path (vertex (edgeSource f)) (vertex (edgeTarget f)) :=
    fun f => Path.segment (vertex (edgeSource f)) (vertex (edgeTarget f))
  refine ⟨Drawing.ofVertexAndEdgePaths vertex hv edge ?_ ?_ ?_⟩
  · intro f _ _ _ _ heq
    exact Path.segment_injective_of_ne (hv.ne (hne f)) heq
  · intro f
    have hne' : vertex (edgeSource f) ≠ vertex (edgeTarget f) := hv.ne (hne f)
    have hnotL : vertex (edgeSource f) ∉
        openSegment ℝ (vertex (edgeSource f)) (vertex (edgeTarget f)) :=
      fun h ↦ hne' (left_mem_openSegment_iff.mp h)
    have hnotR : vertex (edgeTarget f) ∉
        openSegment ℝ (vertex (edgeSource f)) (vertex (edgeTarget f)) :=
      fun h ↦ hne' (right_mem_openSegment_iff.mp h)
    refine disjoint_left.mpr ?_
    rintro z ⟨t, ht, rfl⟩ ⟨v, hvz⟩
    have hzopen : edge f t ∈ openSegment ℝ (vertex (edgeSource f)) (vertex (edgeTarget f)) := by
      simpa [← pathInterior_segment] using ⟨t, ht, rfl⟩
    have hf : (f : β) = e := by simpa [G, edgeSet_singleEdge] using f.2
    have hlink : s((edgeSource f : α), (edgeTarget f : α)) = s(x, y) := by
      simpa [hf, G, singleEdge_isLink_iff] using isLink_edgeSource_edgeTarget f
    have hvxy : (v : α) = x ∨ (v : α) = y := by
      simpa [G, vertexSet_singleEdge] using v.2
    have hmap : vertex v = vertex (edgeSource f) ∨ vertex v = vertex (edgeTarget f) := by
      rcases Sym2.eq_iff.mp hlink with ⟨hs, ht⟩ | ⟨hs, ht⟩
      · rcases hvxy with hvx | hvy
        · exact Or.inl (congrArg vertex (Subtype.ext (hvx.trans hs.symm)))
        · exact Or.inr (congrArg vertex (Subtype.ext (hvy.trans ht.symm)))
      · rcases hvxy with hvx | hvy
        · exact Or.inr (congrArg vertex (Subtype.ext (hvx.trans ht.symm)))
        · exact Or.inl (congrArg vertex (Subtype.ext (hvy.trans hs.symm)))
    rcases hmap with hmap | hmap
    · exact hnotL (by rwa [← hvz, hmap] at hzopen)
    · exact hnotR (by rwa [← hvz, hmap] at hzopen)
  · intro f g hfg
    have hf : (f : β) = e := by simpa [G, edgeSet_singleEdge] using f.2
    have hg : (g : β) = e := by simpa [G, edgeSet_singleEdge] using g.2
    exact (hfg (Subtype.ext (hf.trans hg.symm))).elim

/-- Every finite forest is planar. -/
theorem IsForest.planar [G.Finite] (hG : G.IsForest) : G.Planar := by
  induction hn : V(G).ncard using Nat.strong_induction_on generalizing G with
  | h n ih =>
    subst hn
    obtain hE | hE := E(G).eq_empty_or_nonempty
    · rw [edgeSet_eq_empty_iff.mp hE]
      exact noEdge_planar _ G.vertexSet_finite
    · obtain ⟨ed, xv, hp⟩ := hG.exists_isPendant hE
      obtain ⟨yv, hyV, hlink, hyx, heH, hGeq⟩ := hp.eq_addEdge
      set H := G - ({xv} : Set α)
      have hHplanar : H.Planar :=
        ih V(H).ncard (ncard_delete_vertex_lt hp.vertex_mem) (hG.anti deleteVerts_le) rfl
      have hEplanar : (Graph.singleEdge xv yv ed).Planar := singleEdge_planar hyx.symm ed
      have hedge : Disjoint E(Graph.singleEdge xv yv ed) E(H) := by
        simpa [edgeSet_singleEdge] using (disjoint_singleton_left.mpr heH)
      have hcompat : (Graph.singleEdge xv yv ed).Compatible H :=
        Compatible.of_disjoint_edgeSet hedge
      have hvertex : (V(Graph.singleEdge xv yv ed) ∩ V(H)).Subsingleton := by
        intro a ha b hb
        have ha' : a = yv := by
          have : a ∈ ({xv, yv} : Set α) ∩ V(H) := by simpa [vertexSet_singleEdge] using ha
          have hx : xv ∉ V(H) := by simp [H, vertexSet_deleteVerts]
          simp only [mem_inter_iff, mem_insert_iff, mem_singleton_iff] at this
          obtain ⟨rfl | rfl, haH⟩ := this
          · exact absurd haH hx
          · rfl
        have hb' : b = yv := by
          have : b ∈ ({xv, yv} : Set α) ∩ V(H) := by simpa [vertexSet_singleEdge] using hb
          have hx : xv ∉ V(H) := by simp [H, vertexSet_deleteVerts]
          simp only [mem_inter_iff, mem_insert_iff, mem_singleton_iff] at this
          obtain ⟨rfl | rfl, hbH⟩ := this
          · exact absurd hbH hx
          · rfl
        exact ha'.trans hb'.symm
      have hunion : (Graph.singleEdge xv yv ed ∪ H).Planar :=
        Planar.union_of_vertexSet_inter_subsingleton hEplanar hHplanar hcompat hedge hvertex
      convert hunion
      simpa [Graph.addEdge] using hGeq

/-! ### Straight-line drawing on at most four vertices -/

private def toPlane (x y : ℝ) : Plane := (WithLp.equiv 2 (Fin 2 → ℝ)).symm ![x, y]

@[simp] private lemma toPlane_zero (x y : ℝ) : toPlane x y 0 = x := by simp [toPlane]
@[simp] private lemma toPlane_one (x y : ℝ) : toPlane x y 1 = y := by simp [toPlane]

/-- Four plane points realizing a triangle with an interior vertex: `(0,0)`, `(2,0)`, `(0,2)`,
`(1,1/2)`. -/
private def pts4 : Fin 4 → Plane :=
  ![toPlane 0 0, toPlane 2 0, toPlane 0 2, toPlane 1 (1 / 2)]

private lemma pts4_injective : Injective pts4 := by
  intro a b h
  have hx := congrArg (fun v : Plane => v 0) h
  have hy := congrArg (fun v : Plane => v 1) h
  fin_cases a <;> fin_cases b <;> simp [pts4] at hx hy ⊢

private lemma linInd_of_det {u v : Plane} (h : u 0 * v 1 - u 1 * v 0 ≠ 0) :
    LinearIndependent ℝ ![u, v] := by
  rw [linearIndependent_fin2]
  refine ⟨?_, fun a ha => ?_⟩
  · intro hv
    exact h (by
      have hv0 : v 0 = 0 := by simpa using congrArg (fun w : Plane => w 0) hv
      have hv1 : v 1 = 0 := by simpa using congrArg (fun w : Plane => w 1) hv
      simp [hv0, hv1])
  · have h0 := congrArg (fun w : Plane => w 0) ha
    have h1 := congrArg (fun w : Plane => w 1) ha
    simp [PiLp.smul_apply] at h0 h1
    refine h ?_
    calc
      u 0 * v 1 - u 1 * v 0
          = (a * v 0) * v 1 - (a * v 1) * v 0 := by rw [← h0, ← h1]
        _ = 0 := by ring

private lemma det_pts4_star {c x y : Fin 4} (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    (pts4 x - pts4 c) 0 * (pts4 y - pts4 c) 1 -
      (pts4 x - pts4 c) 1 * (pts4 y - pts4 c) 0 ≠ 0 := by
  fin_cases c <;> fin_cases x <;> fin_cases y <;>
    simp_all [pts4, PiLp.sub_apply] <;> norm_num

private lemma linearIndependent_pts4_star {c x y : Fin 4}
    (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    LinearIndependent ℝ ![pts4 x - pts4 c, pts4 y - pts4 c] :=
  linInd_of_det (det_pts4_star hx hy hxy)

private lemma openSegment_star_disjoint {c x y : Fin 4}
    (hx : x ≠ c) (hy : y ≠ c) (hxy : x ≠ y) :
    Disjoint (openSegment ℝ (pts4 c) (pts4 x)) (openSegment ℝ (pts4 c) (pts4 y)) := by
  refine disjoint_left.2 fun p hpx hpy => ?_
  have hinter : p ∈ segment ℝ (pts4 c) (pts4 x) ∩ segment ℝ (pts4 c) (pts4 y) :=
    ⟨openSegment_subset_segment _ _ _ hpx, openSegment_subset_segment _ _ _ hpy⟩
  have hp : p = pts4 c := by
    have := segment_inter_eq_endpoint_of_linearIndependent_sub ℝ
      (linearIndependent_pts4_star hx hy hxy)
    simpa [this] using hinter
  have : pts4 c = pts4 x := (left_mem_openSegment_iff (y := pts4 x)).mp (by rwa [hp] at hpx)
  exact hx (pts4_injective this.symm)

private lemma not_mem_openSegment_pts4 {i j k : Fin 4}
    (hij : i ≠ j) (hik : k ≠ i) (hjk : k ≠ j) :
    pts4 k ∉ openSegment ℝ (pts4 i) (pts4 j) := by
  intro h
  rw [openSegment_eq_image'] at h
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := h
  have hx := congrArg (fun v : Plane => v 0) heq
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx hy
  fin_cases i <;> fin_cases j <;> fin_cases k <;>
    simp_all [pts4] <;> (try linarith)

private lemma openSegment_eq_of_sym2 {a b c d : Fin 4} (h : s(a, b) = s(c, d)) :
    openSegment ℝ (pts4 a) (pts4 b) = openSegment ℝ (pts4 c) (pts4 d) := by
  rcases (Sym2.eq_iff).mp h with ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩
  · rfl
  · exact openSegment_symm _ _ _

private lemma openSegment_01_23 :
    Disjoint (openSegment ℝ (pts4 0) (pts4 1)) (openSegment ℝ (pts4 2) (pts4 3)) := by
  refine disjoint_left.2 fun p hp01 hp23 => ?_
  rw [openSegment_eq_image'] at hp01 hp23
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp01
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp23
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hy
  have : t = 4 / 3 := by ring_nf at hy; linarith
  linarith

private lemma openSegment_02_13 :
    Disjoint (openSegment ℝ (pts4 0) (pts4 2)) (openSegment ℝ (pts4 1) (pts4 3)) := by
  refine disjoint_left.2 fun p hp01 hp23 => ?_
  rw [openSegment_eq_image'] at hp01 hp23
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp01
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp23
  have hx := congrArg (fun v : Plane => v 0) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx
  have : t = 2 := by linarith
  linarith

private lemma openSegment_12_03 :
    Disjoint (openSegment ℝ (pts4 1) (pts4 2)) (openSegment ℝ (pts4 0) (pts4 3)) := by
  refine disjoint_left.2 fun p hp12 hp03 => ?_
  rw [openSegment_eq_image'] at hp12 hp03
  obtain ⟨s, ⟨hs0, hs1⟩, rfl⟩ := hp12
  obtain ⟨t, ⟨ht0, ht1⟩, heq⟩ := hp03
  have hx := congrArg (fun v : Plane => v 0) heq
  have hy := congrArg (fun v : Plane => v 1) heq
  simp [pts4, PiLp.add_apply, PiLp.sub_apply, PiLp.smul_apply] at hx hy
  have hs : s = 1 / 3 := by
    have ht : t = 2 - 2 * s := by linarith
    have : 2 * s = t / 2 := by linarith
    rw [ht] at this; linarith
  have : t = 4 / 3 := by linarith
  linarith

private lemma exists_canon_edge {a b : Fin 4} (hab : a ≠ b) :
    ∃ u v : Fin 4, u < v ∧ s(a, b) = s(u, v) := by
  wlog hlt : a < b generalizing a b
  · obtain ⟨u, v, huv, heq⟩ := this hab.symm (lt_of_le_of_ne (le_of_not_gt hlt) hab.symm)
    exact ⟨u, v, huv, by simpa [Sym2.eq_swap] using heq⟩
  exact ⟨a, b, hlt, rfl⟩

private lemma openSegment_pts4_disjoint_complementary {u v u' v' : Fin 4}
    (huv : u < v) (huv' : u' < v') (hne : s(u, v) ≠ s(u', v'))
    (hdisj : Disjoint ({u, v} : Set (Fin 4)) {u', v'}) :
    Disjoint (openSegment ℝ (pts4 u) (pts4 v)) (openSegment ℝ (pts4 u') (pts4 v')) := by
  fin_cases u <;> fin_cases v <;> fin_cases u' <;> fin_cases v' <;>
    simp_all [Fin.lt_def] <;>
    first
    | exact openSegment_01_23
    | exact openSegment_02_13
    | exact openSegment_12_03
    | exact openSegment_01_23.symm
    | exact openSegment_02_13.symm
    | exact openSegment_12_03.symm

private lemma openSegment_pts4_disjoint {i j k ℓ : Fin 4}
    (hij : i ≠ j) (hkl : k ≠ ℓ) (hne : s(i, j) ≠ s(k, ℓ)) :
    Disjoint (openSegment ℝ (pts4 i) (pts4 j)) (openSegment ℝ (pts4 k) (pts4 ℓ)) := by
  obtain ⟨u, v, huv, heq1⟩ := exists_canon_edge hij
  obtain ⟨u', v', huv', heq2⟩ := exists_canon_edge hkl
  have hne' : s(u, v) ≠ s(u', v') := fun h => hne (heq1.trans (h.trans heq2.symm))
  rw [openSegment_eq_of_sym2 heq1, openSegment_eq_of_sym2 heq2]
  by_cases hshare : ({u, v} ∩ {u', v'} : Set (Fin 4)).Nonempty
  · obtain ⟨c, hc⟩ := hshare
    have hc1 : c ∈ ({u, v} : Set _) := hc.1
    have hc2 : c ∈ ({u', v'} : Set _) := hc.2
    let x : Fin 4 := if c = u then v else u
    let y : Fin 4 := if c = u' then v' else u'
    have hx : x ≠ c := by
      dsimp [x]; split_ifs with hcu
      · exact hcu ▸ huv.ne'
      · have : c = v := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc1
          exact hc1.resolve_left hcu
        exact this ▸ huv.ne
    have hy : y ≠ c := by
      dsimp [y]; split_ifs with hcu
      · exact hcu ▸ huv'.ne'
      · have : c = v' := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc2
          exact hc2.resolve_left hcu
        exact this ▸ huv'.ne
    have hxy : x ≠ y := by
      intro heqxy
      apply hne'
      have e1 : s(u, v) = s(c, x) := by
        dsimp [x]; split_ifs with hcu
        · subst hcu; rfl
        · have : c = v := by
            simp only [mem_insert_iff, mem_singleton_iff] at hc1
            exact hc1.resolve_left hcu
          subst this; exact Sym2.eq_swap
      have e2 : s(u', v') = s(c, y) := by
        dsimp [y]; split_ifs with hcu
        · subst hcu; rfl
        · have : c = v' := by
            simp only [mem_insert_iff, mem_singleton_iff] at hc2
            exact hc2.resolve_left hcu
          subst this; exact Sym2.eq_swap
      exact e1.trans (heqxy ▸ e2.symm)
    have e1 : openSegment ℝ (pts4 u) (pts4 v) = openSegment ℝ (pts4 c) (pts4 x) := by
      dsimp [x]; split_ifs with hcu
      · subst hcu; rfl
      · have : c = v := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc1
          exact hc1.resolve_left hcu
        subst this; exact openSegment_symm _ _ _
    have e2 : openSegment ℝ (pts4 u') (pts4 v') = openSegment ℝ (pts4 c) (pts4 y) := by
      dsimp [y]; split_ifs with hcu
      · subst hcu; rfl
      · have : c = v' := by
          simp only [mem_insert_iff, mem_singleton_iff] at hc2
          exact hc2.resolve_left hcu
        subst this; exact openSegment_symm _ _ _
    rw [e1, e2]
    exact openSegment_star_disjoint hx hy hxy
  · push Not at hshare
    have hdisj : Disjoint ({u, v} : Set (Fin 4)) {u', v'} := by
      rw [disjoint_iff_inter_eq_empty]; simpa using hshare
    exact openSegment_pts4_disjoint_complementary huv huv' hne' hdisj

/-- Every finite simple graph on at most four vertices is planar.

This is proved by a straight-line drawing with vertices at
`(0,0)`, `(2,0)`, `(0,2)`, `(1,1/2)` (triangle plus interior point) and edges as segments,
fed to `Drawing.ofVertexAndEdgePaths`. -/
theorem planar_of_vertexSet_encard_le_four [G.Finite] [G.Simple]
    (hG : V(G).encard ≤ 4) : G.Planar := by
  have : Fintype V(G) := Fintype.ofFinite _
  have hcard : Fintype.card V(G) ≤ 4 := by
    have heq : V(G).encard = (Fintype.card V(G) : ℕ∞) := by
      rw [Set.encard_eq_coe_toFinset_card, Set.toFinset_card]
    have : ((Fintype.card V(G) : ℕ) : ℕ∞) ≤ 4 := by rwa [← heq]
    exact Nat.cast_le.mp this
  let ι : V(G) ↪ Fin 4 :=
    (Fintype.equivFin V(G)).toEmbedding.trans (Fin.castLEEmb hcard)
  set vertex : V(G) → Plane := pts4 ∘ ι
  have hv : Injective vertex := pts4_injective.comp ι.injective
  have hne : ∀ e : E(G), edgeSource e ≠ edgeTarget e := by
    intro e heq
    exact (isLink_edgeSource_edgeTarget e).ne (congrArg Subtype.val heq)
  set edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)) :=
    fun e => Path.segment (vertex (edgeSource e)) (vertex (edgeTarget e))
  refine ⟨Drawing.ofVertexAndEdgePaths vertex hv edge ?_ ?_ ?_⟩
  · intro e _ _ _ _ heq
    exact Path.segment_injective_of_ne (hv.ne (hne e)) heq
  · intro e
    rw [pathInterior_segment]
    refine disjoint_left.mpr ?_
    rintro z hz ⟨w, rfl⟩
    have hij : ι (edgeSource e) ≠ ι (edgeTarget e) := ι.injective.ne (hne e)
    have hz' : pts4 (ι w) ∈
        openSegment ℝ (pts4 (ι (edgeSource e))) (pts4 (ι (edgeTarget e))) := by
      simpa [vertex] using hz
    by_cases h1 : ι w = ι (edgeSource e)
    · rw [h1] at hz'
      exact hij (pts4_injective (left_mem_openSegment_iff.mp hz'))
    · by_cases h2 : ι w = ι (edgeTarget e)
      · rw [h2] at hz'
        exact hij (pts4_injective (right_mem_openSegment_iff.mp hz'))
      · exact not_mem_openSegment_pts4 hij h1 h2 hz'
  · intro e f hef
    rw [pathInterior_segment, pathInterior_segment]
    have hij : ι (edgeSource e) ≠ ι (edgeTarget e) := ι.injective.ne (hne e)
    have hkl : ι (edgeSource f) ≠ ι (edgeTarget f) := ι.injective.ne (hne f)
    have hends : G.ends e ≠ G.ends f := (ends_injective G).ne hef
    have hne_sym : s(ι (edgeSource e), ι (edgeTarget e)) ≠
        s(ι (edgeSource f), ι (edgeTarget f)) := by
      intro heq
      apply hends
      have he : G.ends e = s(edgeSource e, edgeTarget e) :=
        (isLink_edgeSource_edgeTarget e).ends_eq
      have hf : G.ends f = s(edgeSource f, edgeTarget f) :=
        (isLink_edgeSource_edgeTarget f).ends_eq
      refine (Sym2.map.injective ι.injective) ?_
      simpa [he, hf, Sym2.map_mk] using heq
    simpa [vertex] using openSegment_pts4_disjoint hij hkl hne_sym


/-! ### Kuratowski obstructions -/

/- **Rejected route** (Status.md §11.2). `Drawing.exists_plDrawing` / `Planar.plPlanar` are proved
(`PLReduction.lean`). Assume `not_alternating_crosscut` (`ThetaCurve.lean`) as proved (formalisation
helper owns the θ-cover bridge). Still not a tactic fill: there is no named Lean bridge from a
`PLDrawing` of `CompleteGraph 5` to the polygon `J` on vertices `1,2,3,4` and the two crosscut arcs
of §11.2 — escalate that scaffolding. -/
/-- The complete graph on five vertices is not planar. -/
theorem not_planar_completeGraph_five : ¬ (CompleteGraph 5).Planar := by
  sorry

/- **Rejected route** (Status.md §11.3). Same as `not_planar_completeGraph_five`: PL reduction is
in, θ/alternating assumed; missing named bridge from a `PLDrawing` of `CompleteBipartiteGraph 3 3`
to the 4-cycle polygon and through-vertex arcs `A`, `B` of §11.3. -/
/-- The complete bipartite graph with two parts of size three is not planar. -/
theorem not_planar_completeBipartiteGraph_three_three :
    ¬ (CompleteBipartiteGraph 3 3).Planar := by
  sorry

/- **Rejected route** (Status.md §11.4 →). Local proof is
`fun h ↦ not_planar_completeGraph_five (hG.isTopologicalMinor h)`, blocked on
`IsDrawable.isTopologicalMinor` (`:670`, `sorry`) and the K₅ nonplanarity lemma above. -/
/-- A planar graph has no topological `K₅`. -/
theorem Planar.not_isTopologicalMinor_completeGraph_five (hG : G.Planar) :
    ¬ (CompleteGraph 5).IsTopologicalMinor G := by
  sorry

/- **Rejected route** (Status.md §11.4 →). Same shape as the `K₅` case:
`fun h ↦ not_planar_completeBipartiteGraph_three_three (hG.isTopologicalMinor h)`, blocked on
`IsDrawable.isTopologicalMinor` (`:670`) and `not_planar_completeBipartiteGraph_three_three`. -/
/-- A planar graph has no topological `K₃,₃`. -/
theorem Planar.not_isTopologicalMinor_completeBipartiteGraph_three_three
    (hG : G.Planar) :
    ¬ (CompleteBipartiteGraph 3 3).IsTopologicalMinor G := by
  sorry

end

end Graph
