import Matroid.Graph.Degree.Max
import Matroid.Graph.Minor.Defs
import Matroid.Graph.Planarity.Realization.Subgraph
import Matroid.Graph.TopologicalMinor

/-!
# Drawings of graphs

This file defines a drawing of a graph in an arbitrary topological space to be a continuous
injection from the weak realization of the graph. It also records the construction and transport
statements needed for the topological formulation of Kuratowski's theorem.

The plane-specific part of the API is deliberately small. The difficult local topology used to
split a contracted vertex is hidden behind
`Graph.Drawing.isPlanar_of_contract_of_facial_cycle_two_paths`.

## Main definitions

- `Graph.Drawing`: a continuous injection from the weak realization of a graph.
- `Graph.IsDrawable`: existence of a drawing in a specified topological space.
- `Graph.IsPlanar`: existence of a drawing in the Euclidean plane.
- `Graph.Drawing.Face`: a connected component of the complement of a drawing.
- `Graph.Drawing.IsFacialSubgraph`: a subgraph whose drawing is the frontier of a face.

## Main statements

- `Graph.Drawing.ofVertexAndEdgePaths`: construct a drawing from pairwise internally disjoint edge
  paths.
- `Graph.Drawing.restrict`: restrict a drawing to a subgraph.
- `Graph.Drawing.exists_facial_cycle_of_delete_vertex`: deleting a vertex of a 3-connected plane
  drawing exposes its neighbors on a facial cycle.
- `Graph.Drawing.isPlanar_of_contract_of_facial_cycle_two_paths`: split a contracted vertex when
  the two sets of neighbors occur on two sides of a facial cycle.
- `Graph.IsPlanar.isTopologicalMinor`: planarity is inherited by topological minors.

## Implementation notes

`Graph.Drawing` contains only continuity and injectivity. Compactness, separation, simplicity, and
finiteness are not part of the definition.

## Tags

graph drawing, graph embedding, planar graph, Kuratowski theorem
-/

open Function Set Topology
open scoped unitInterval

namespace Graph

noncomputable section

universe u v w

variable {α β γ δ : Type*} {G H : Graph α β} {K : Graph γ δ} {e : β} {u v : α}
variable {X : Type u} {Y : Type v} [TopologicalSpace X] [TopologicalSpace Y]

/-- A drawing of `G` in `X` is a continuous injection from the weak realization of `G` to `X`. -/
structure Drawing (G : Graph α β) (X : Type u) [TopologicalSpace X] extends
    C(Realization G, X), Realization G ↪ X

-- This parent projection is generated by the `extends` command.
attribute [nolint docBlame] Drawing.toEmbedding

namespace Drawing

variable {D D' : Drawing G X}

instance : FunLike (Drawing G X) (Realization G) X where
  coe D := D.toContinuousMap
  coe_injective D₁ D₂ h := by
    cases D₁
    cases D₂
    simpa using h

instance : ContinuousMapClass (Drawing G X) (Realization G) X where
  map_continuous D := D.toContinuousMap.continuous

instance : EmbeddingLike (Drawing G X) (Realization G) X where
  injective' D := D.toEmbedding.injective

@[ext]
theorem ext {D₁ D₂ : Drawing G X} (h : ∀ x, D₁ x = D₂ x) : D₁ = D₂ :=
  DFunLike.coe_injective <| funext h

@[simp]
lemma coe_toContinuousMap (D : Drawing G X) : ⇑D.toContinuousMap = D := rfl

/-- A drawing is continuous. -/
lemma continuous (D : Drawing G X) : Continuous D :=
  D.toContinuousMap.continuous

/-- A drawing is injective. -/
lemma injective (D : Drawing G X) : Injective D :=
  D.toEmbedding.injective

/-- The point assigned by a drawing to a vertex. -/
def vertex (D : Drawing G X) (x : V(G)) : X :=
  D (vertexMk x)

/-- The path assigned by a drawing to an edge. -/
noncomputable def edgePath (D : Drawing G X) (e : E(G)) :
    Path (D.vertex (edgeSource e)) (D.vertex (edgeTarget e)) :=
  (G.edgePath e).map D.continuous

/-- The open image of a path, with both endpoints omitted. -/
def pathInterior {x y : X} (P : Path x y) : Set X :=
  P '' Ioo (0 : unitInterval) 1

/-- The image of the realization under a drawing. -/
def support (D : Drawing G X) : Set X :=
  range D

@[simp]
lemma vertex_mem_support (D : Drawing G X) (x : V(G)) : D.vertex x ∈ D.support :=
  ⟨vertexMk x, rfl⟩

lemma edgePath_range_subset_support (D : Drawing G X) (e : E(G)) :
    range (D.edgePath e) ⊆ D.support := by
  rintro _ ⟨t, rfl⟩
  refine ⟨G.edgePath e t, rfl⟩

/-- Distinct vertices have distinct images in a drawing. -/
lemma vertex_injective (D : Drawing G X) : Injective D.vertex :=
  fun _ _ hxy ↦ vertexMk_inj.mp <| D.injective hxy

/-- The open part of each edge path is injectively parametrized. -/
lemma edgePath_injOn_Ioo (D : Drawing G X) (e : E(G)) :
    InjOn (D.edgePath e) (Ioo (0 : unitInterval) 1) := by
  sorry

/-- The open part of an edge is disjoint from all vertex images. -/
lemma pathInterior_edgePath_disjoint_vertex (D : Drawing G X) (e : E(G)) :
    Disjoint (pathInterior (D.edgePath e)) (range D.vertex) := by
  sorry

/-- The open parts of distinct edges are disjoint. -/
lemma pathInterior_edgePath_disjoint (D : Drawing G X) {e f : E(G)} (hef : e ≠ f) :
    Disjoint (pathInterior (D.edgePath e)) (pathInterior (D.edgePath f)) := by
  sorry

/-- The support of a drawing of a finite graph is compact. -/
lemma support_isCompact [G.Finite] (D : Drawing G X) : IsCompact D.support :=
  isCompact_range D.continuous

/-- In a Hausdorff space, the support of a drawing of a finite graph is closed. -/
lemma support_isClosed [G.Finite] [T2Space X] (D : Drawing G X) : IsClosed D.support :=
  D.support_isCompact.isClosed

/-- Postcompose a drawing with a continuous injection of ambient spaces. -/
def postcomp (D : Drawing G X) (f : C(X, Y)) (hf : Injective f) : Drawing G Y where
  toContinuousMap := f.comp D.toContinuousMap
  inj' := hf.comp D.injective

@[simp]
lemma postcomp_apply (D : Drawing G X) (f : C(X, Y)) (hf : Injective f)
    (x : Realization G) : D.postcomp f hf x = f (D x) :=
  rfl

/-! ### Constructors -/

/-- Construct a drawing from a map on the pre-realization that identifies exactly the points
identified by the realization quotient. -/
noncomputable def ofPreRealization (f : C(G.PreRealization, X))
    (map_eq_of_glueRel : ∀ a b, G.glueRel a b → f a = f b)
    (glueRel_of_map_eq : ∀ a b, f a = f b → G.glueRel a b) : Drawing G X := by
  sorry

/-- Construct a drawing by assigning distinct points to vertices and internally disjoint paths to
edges.

The hypotheses allow loops and parallel edges. For a loop, the two endpoints of its path agree,
as prescribed by `edgeSource` and `edgeTarget`; only the open interval is required to be
injective. -/
noncomputable def ofVertexAndEdgePaths
    (vertex : V(G) → X) (vertex_injective : Injective vertex)
    (edge : ∀ e : E(G), Path (vertex (edgeSource e)) (vertex (edgeTarget e)))
    (edge_injective : ∀ e, InjOn (edge e) (Ioo (0 : unitInterval) 1))
    (edge_interior_disjoint_vertex : ∀ e, Disjoint (pathInterior (edge e)) (range vertex))
    (edge_interior_disjoint : ∀ e f, e ≠ f →
      Disjoint (pathInterior (edge e)) (pathInterior (edge f))) :
    Drawing G X := by
  sorry

/-- The empty graph has a drawing in every topological space, including the empty space. -/
noncomputable def bot (X : Type u) [TopologicalSpace X] : Drawing (⊥ : Graph α β) X := by
  sorry

/-! ### Restriction and transport -/

/-- Restrict a drawing to a subgraph. -/
def restrict (D : Drawing G X) (h : H ≤ G) : Drawing H X where
  toContinuousMap := D.toContinuousMap.comp h.realizationContinuousMap
  inj' := D.injective.comp h.RealizationEmbedding_isEmbedding.injective

@[simp]
lemma restrict_apply (D : Drawing G X) (h : H ≤ G) (x : Realization H) :
    D.restrict h x = D (h.RealizationEmbedding x) := rfl

end Drawing

namespace Iso

/-- The homeomorphism of weak realizations induced by a graph isomorphism. -/
noncomputable def realizationHomeomorph (F : Iso K G) :
    Realization K ≃ₜ Realization G := by
  sorry

end Iso

namespace Drawing

/-- Pull a drawing back along a graph isomorphism. -/
noncomputable def ofIso (D : Drawing G X) (F : Iso K G) : Drawing K X where
  toContinuousMap :=
    { toFun := D ∘ F.realizationHomeomorph
      continuous_toFun := D.continuous.comp F.realizationHomeomorph.continuous }
  inj' := D.injective.comp F.realizationHomeomorph.injective

/-- A drawing `D'` extends `D` along the subgraph inclusion `h`. -/
def Extends (D' : Drawing G X) (D : Drawing H X) (h : H ≤ G) : Prop :=
  ∀ x, D' (h.RealizationEmbedding x) = D x

/-! ### Faces -/

/-- The faces of a drawing are the connected components of its complement. -/
def Face (D : Drawing G X) : Type u := ConnectedComponents ↑(D.supportᶜ)

/-- The subset of the ambient space belonging to a face. -/
def faceSet (D : Drawing G X) (F : D.Face) : Set X :=
  Subtype.val '' ConnectedComponents.mk ⁻¹' {F}

/-- Every face contains a point. -/
lemma faceSet_nonempty (D : Drawing G X) (F : D.Face) : (D.faceSet F).Nonempty := by
  sorry

/-- A face is disjoint from the drawing. -/
lemma faceSet_disjoint_support (D : Drawing G X) (F : D.Face) :
    Disjoint (D.faceSet F) D.support := by
  sorry

/-- The face containing `x` is its connected component in the complement of the drawing. -/
lemma faceSet_eq_connectedComponentIn (D : Drawing G X) (F : D.Face) (x : X)
    (hx : x ∈ D.faceSet F) :
    D.faceSet F = connectedComponentIn D.supportᶜ x := by
  sorry

/-- A face is connected. -/
lemma faceSet_isConnected (D : Drawing G X) (F : D.Face) : IsConnected (D.faceSet F) := by
  sorry

/-- A face of a finite drawing in a locally connected Hausdorff space is open. -/
lemma faceSet_isOpen [G.Finite] [T2Space X] [LocallyConnectedSpace X]
    (D : Drawing G X) (F : D.Face) : IsOpen (D.faceSet F) := by
  sorry

/-- The frontier of a face of a finite drawing lies in the support of the drawing. -/
lemma frontier_faceSet_subset_support [G.Finite] [T2Space X] [LocallyConnectedSpace X]
    (D : Drawing G X) (F : D.Face) : frontier (D.faceSet F) ⊆ D.support := by
  sorry

/-- A subgraph is facial in `D` if its drawing is exactly the frontier of a face. -/
def IsFacialSubgraph (D : Drawing G X) (h : H ≤ G) : Prop :=
  ∃ F : D.Face, frontier (D.faceSet F) = (D.restrict h).support



/-! ### Drawability and planarity -/

end Drawing

/-- A graph is drawable in `X` if its weak realization admits a continuous injection into `X`. -/
def IsDrawable (G : Graph α β) (X : Type u) [TopologicalSpace X] : Prop :=
  Nonempty (Drawing G X)

/-- A graph is planar if it has a drawing in the Euclidean plane. -/
def IsPlanar (G : Graph α β) : Prop :=
  G.IsDrawable (EuclideanSpace ℝ (Fin 2))

/-- The empty graph is drawable in every topological space. -/
theorem bot_isDrawable (X : Type u) [TopologicalSpace X] :
    (⊥ : Graph α β).IsDrawable X :=
  ⟨Drawing.bot X⟩

/-- The empty graph is planar. -/
theorem bot_isPlanar : (⊥ : Graph α β).IsPlanar :=
  bot_isDrawable (EuclideanSpace ℝ (Fin 2))

namespace IsDrawable

/-- Drawability is inherited by subgraphs. -/
lemma anti (hG : G.IsDrawable X) (hHG : H ≤ G) : H.IsDrawable X :=
  ⟨hG.some.restrict hHG⟩

/-- Drawability is invariant under graph isomorphism. -/
lemma of_iso (hG : G.IsDrawable X) (F : Iso K G) : K.IsDrawable X :=
  ⟨hG.some.ofIso F⟩

/-- Drawability is inherited by topological minors. -/
theorem isMinor (hG : G.IsDrawable X) (hHG : H.IsMinor G) : H.IsDrawable X := by
  sorry

end IsDrawable

namespace IsPlanar

/-- Planarity is inherited by subgraphs. -/
lemma anti (hG : G.IsPlanar) (hHG : H ≤ G) : H.IsPlanar :=
  IsDrawable.anti hG hHG

/-- Planarity is invariant under graph isomorphism. -/
lemma of_iso (hG : G.IsPlanar) (F : Iso K G) : K.IsPlanar :=
  IsDrawable.of_iso hG F

/-- Planarity is inherited by minors. -/
theorem isMinor (hG : G.IsPlanar) (hHG : H.IsMinor G) : H.IsPlanar :=
  IsDrawable.isMinor hG hHG

/-- The union of two finite planar graphs meeting in at most one vertex is planar. -/
theorem union_of_vertexSet_inter_subsingleton {G₁ G₂ : Graph α β} [G₁.Finite] [G₂.Finite]
    (h₁ : G₁.IsPlanar) (h₂ : G₂.IsPlanar) (hcompat : G₁.Compatible G₂)
    (hedge : Disjoint E(G₁) E(G₂)) (hvertex : (V(G₁) ∩ V(G₂)).Subsingleton) :
    (G₁ ∪ G₂).IsPlanar := by
  sorry

/-- The union of two finite planar graphs along a common nonloop edge is planar. -/
theorem union_of_common_nonloop_edge {G₁ G₂ : Graph α β} [G₁.Finite] [G₂.Finite]
    (h₁ : G₁.IsPlanar) (h₂ : G₂.IsPlanar) (hcompat : G₁.Compatible G₂)
    (he₁ : G₁.IsLink e u v) (he₂ : G₂.IsLink e u v) (huv : u ≠ v)
    (hvertex : V(G₁) ∩ V(G₂) = {u, v}) (hedge : E(G₁) ∩ E(G₂) = {e}) :
    (G₁ ∪ G₂).IsPlanar := by
  sorry

end IsPlanar

/-- Every finite forest is planar. -/
theorem IsForest.isPlanar [G.Finite] (hG : G.IsForest) : G.IsPlanar := by
  sorry

/-- Every finite simple graph on at most four vertices is planar. -/
theorem isPlanar_of_vertexSet_encard_le_four [G.Finite] [G.Simple]
    (hG : V(G).encard ≤ 4) : G.IsPlanar := by
  sorry

/-! ### Plane topology used in the 3-connected case -/

namespace Drawing

variable {e : β} {u v : α} {C : Graph α β} {P₁ P₂ : WList α β}

/-- In a plane drawing of a finite 3-connected graph, deleting a vertex produces a face whose
frontier is a cycle containing every neighbor of the deleted vertex. -/
theorem exists_facial_cycle_of_delete_vertex [H.Finite] [H.Simple] (hH : H.ConnGE 3)
    (D : Drawing H (EuclideanSpace ℝ (Fin 2))) (u : V(H)) :
    ∃ (C : Graph α β) (hC : C ≤ H - {u.1}),
      C.IsCycle ∧ (D.restrict deleteVerts_le).IsFacialSubgraph hC ∧ N(H, u.1) ⊆ V(C) := by
  sorry

/-- The facial cycle around the contracted vertex, expressed back in the original graph.

This packages the carrier bookkeeping between `(G /(e, he)) - {u}` and `G - {u, v}`. In
particular, every neighbor of either endpoint other than the other endpoint lies on the cycle. -/
theorem exists_facial_cycle_of_contract [G.Finite] [G.Simple]
    (he : G.IsLink e u v) (huv : u ≠ v) (hcontract : (G /(e, he)).ConnGE 3)
    (D : Drawing (G /(e, he)) (EuclideanSpace ℝ (Fin 2))) :
    ∃ (C : Graph α β) (hCG : C ≤ G) (hCcontract : C ≤ (G /(e, he)) - {u}),
      C.IsCycle ∧ (D.restrict deleteVerts_le).IsFacialSubgraph hCcontract ∧
      u ∉ V(C) ∧ v ∉ V(C) ∧ N(G, u) \ {v} ⊆ V(C) ∧ N(G, v) \ {u} ⊆ V(C) := by
  sorry

/-- The local vertex-splitting step used in the 3-connected case of Kuratowski's theorem.

Suppose `e` joins `u` and `v`, the contraction of `e` has a plane drawing, and deleting the
contracted vertex exposes a facial cycle `C`. If `C` is the union of two paths such that the
interior of the first contains no neighbor of `u` and the interior of the second contains no
neighbor of `v`, then the contracted vertex can be split inside that face to obtain a drawing of
`G`.

The last five hypotheses deliberately have the same shape as the first conclusion of
`Graph.K33_K5_lemma`. -/
theorem isPlanar_of_contract_of_facial_cycle_two_paths [G.Finite] [G.Simple]
    (he : G.IsLink e u v) (huv : u ≠ v)
    (D : Drawing (G /(e, he)) (EuclideanSpace ℝ (Fin 2)))
    (hCG : C ≤ G) (hCcontract : C ≤ (G /(e, he)) - {u}) (hcycle : C.IsCycle)
    (hfacial : (D.restrict deleteVerts_le).IsFacialSubgraph hCcontract)
    (hu_neighbors : N(G, u) \ {v} ⊆ V(C)) (hv_neighbors : N(G, v) \ {u} ⊆ V(C))
    (hP₁ : C.IsPath P₁) (hP₂ : C.IsPath P₂)
    (huP₁ : ∀ x ∈ P₁.vertex.tail.dropLast, ¬ G.Adj u x)
    (hvP₂ : ∀ x ∈ P₂.vertex.tail.dropLast, ¬ G.Adj v x)
    (hP₁P₂ : C.IsCyclicWalk (P₁ ++ P₂)) :
    G.IsPlanar := by
  sorry

end Drawing

/-! ### Kuratowski obstructions -/

/-- The complete graph on five vertices is not planar. -/
theorem not_isPlanar_completeGraph_five : ¬ (CompleteGraph 5).IsPlanar := by
  sorry

/-- The complete bipartite graph with two parts of size three is not planar. -/
theorem not_isPlanar_completeBipartiteGraph_three_three :
    ¬ (CompleteBipartiteGraph 3 3).IsPlanar := by
  sorry

/-- A planar graph has no topological `K₅`. -/
theorem IsPlanar.not_isTopologicalMinor_completeGraph_five (hG : G.IsPlanar) :
    ¬ (CompleteGraph 5).IsTopologicalMinor G := by
  sorry

/-- A planar graph has no topological `K₃,₃`. -/
theorem IsPlanar.not_isTopologicalMinor_completeBipartiteGraph_three_three
    (hG : G.IsPlanar) :
    ¬ (CompleteBipartiteGraph 3 3).IsTopologicalMinor G := by
  sorry

end

end Graph
